/**
 * Created by bradflyon on 5/15/14.
 */

var judges = [

    {name:"John G. Roberts, Jr"
        , title:"Chief Justice of the United States"
        , img:"sc_JRoberts.jpg"
        , imgSource:"http://www.supremecourt.gov/about/justice_pictures/JRoberts.jpg"
        , court:"SCOTUS"
        , nominatedBy:{name:"President George W. Bush", party:"R", year:2005}
        , url:"http://www.supremecourt.gov/about/biographies.aspx"
    }
    ,
    {name:"Antonio Scalia"
        , title:"Associate Justice"
        , img:"sc_AScalia2.jpg"
        , imgSource:"http://www.supremecourt.gov/about/justice_pictures/AScalia2.jpg"
        , court:"SCOTUS"
        , nominatedBy:{name:"President Ronald Reagan", party:"R", year:1986}
        , url:"http://www.supremecourt.gov/about/biographies.aspx"
    }
    ,
    {name:"Anthony M. Kennedy"
        , title:"Associate Justice"
        , img:"sc_AKennedy.jpg"
        , imgSource:"http://www.supremecourt.gov/about/justice_pictures/AKennedy.jpg"
        , court:"SCOTUS"
        , nominatedBy:{name:"President Ronald Reagan", party:"R", year:1988}
        , url:"http://www.supremecourt.gov/about/biographies.aspx"
    }
    , {name:"Clarence Thomas"
        , title:"Associate Justice"
        , img:"sc_CThomas.jpg"
        , imgSource:"http://www.supremecourt.gov/about/justice_pictures/CThomas.jpg"
        , court:"SCOTUS"
        , nominatedBy:{name:"President George Bush", party:"R", year:1991}
        , url:"http://www.supremecourt.gov/about/biographies.aspx"
    }
    , {name:"Ruth Bader Ginsburg"
        , title:"Associate Justice"
        , img:"sc_RGinsburg2.jpg"
        , imgSource:"http://www.supremecourt.gov/about/justice_pictures/RGinsburg2.jpg"
        , court:"SCOTUS"
        , nominatedBy:{name:"President Clinton", party:"D", year:1993}
        , url:"http://www.supremecourt.gov/about/biographies.aspx"
    }
    , {name:"Stephen G. Breyer"
        , title:"Associate Justice"
        , img:"sc_SBreyer.jpg"
        , imgSource:"http://www.supremecourt.gov/about/justice_pictures/SBreyer.jpg"
        , court:"SCOTUS"
        , nominatedBy:{name:"President Clinton", party:"D", year:1994}
        , url:"http://www.supremecourt.gov/about/biographies.aspx"
    }
    , {name:"Samuel Anthony Alito, Jr."
        , title:"Associate Justice"
        , img:"sc_SAlito.jpg"
        , imgSource:"http://www.supremecourt.gov/about/justice_pictures/SAlito.jpg"
        , court:"SCOTUS"
        , nominatedBy:{name:"President George W. Bush", party:"R", year:2006}
        , url:"http://www.supremecourt.gov/about/biographies.aspx"
    }
    , {name:"Sonia Sotomayor"
        , title:"Associate Justice"
        , img:"sc_SSotomayor.jpg"
        , imgSource:"http://www.supremecourt.gov/about/justice_pictures/SSotomayor.jpg.jpg"
        , court:"SCOTUS"
        , nominatedBy:{name:"President Barack Obama", party:"D", year:2009}
        , url:"http://www.supremecourt.gov/about/biographies.aspx"
    }
    , {name:"Elena Kagan"
        , title:"Associate Justice"
        , img:"sc_EKagan.jpg"
        , imgSource:"http://www.supremecourt.gov/about/justice_pictures/EKagan.jpg.jpg"
        , court:"SCOTUS"
        , nominatedBy:{name:"President Barack Obama", party:"D", year:2010}
        , url:"http://www.supremecourt.gov/about/biographies.aspx"
    }

    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_First_Circuit', name:'Sandra Lynch', title:'Chief Judge', born:'1946',  court:'1st Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1995'},url:'http://en.wikipedia.org/wiki/Sandra_Lynch', dutyStation:'Boston, MA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_First_Circuit', name:'Juan R. Torruella', title:'Circuit Judge', born:'1933',  court:'1st Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1984'},url:'http://en.wikipedia.org/wiki/Juan_R._Torruella', dutyStation:'San Juan, PR'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_First_Circuit', name:'Jeffrey R. Howard', title:'Circuit Judge', born:'1955',  court:'1st Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2002'},url:'http://en.wikipedia.org/wiki/Jeffrey_R._Howard', dutyStation:'Concord, NH'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_First_Circuit', name:'Ojetta Rogeriee Thompson', title:'Circuit Judge', born:'1951',  court:'1st Cir.', nominatedBy:{name:'Obama', party:'D', year:'2010'},url:'http://en.wikipedia.org/wiki/Ojetta_Rogeriee_Thompson', dutyStation:'Providence, RI'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_First_Circuit', name:'William J. Kayatta, Jr.', title:'Circuit Judge', born:'1953',  court:'1st Cir.', nominatedBy:{name:'Obama', party:'D', year:'2013'},url:'http://en.wikipedia.org/wiki/William_J._Kayatta,_Jr.', dutyStation:'Portland, ME'}

    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_First_Circuit', name:'Levin H. Campbell', title:'Senior Judge', born:'1927',  court:'1st Cir.', nominatedBy:{name:'Nixon', party:'R', year:'1972'},url:'http://en.wikipedia.org/wiki/Levin_H._Campbell', dutyStation:'inactive'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_First_Circuit', name:'Bruce M. Selya', title:'Senior Judge', born:'1934',  court:'1st Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1986'},url:'http://en.wikipedia.org/wiki/Bruce_M._Selya', dutyStation:'Providence, RI'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_First_Circuit', name:'Conrad K. Cyr', title:'Senior Judge', born:'1931',  court:'1st Cir.', nominatedBy:{name:'G.H.W. Bush', party:'R', year:'1989'},url:'http://en.wikipedia.org/wiki/Conrad_K._Cyr', dutyStation:'inactive'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_First_Circuit', name:'Michael Boudin', title:'Senior Judge', born:'1939',  court:'1st Cir.', nominatedBy:{name:'G.H.W. Bush', party:'R', year:'1992'},url:'http://en.wikipedia.org/wiki/Michael_Boudin', dutyStation:'Boston, MA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_First_Circuit', name:'Norman H. Stahl', title:'Senior Judge', born:'1931',  court:'1st Cir.', nominatedBy:{name:'G.H.W. Bush', party:'R', year:'1992'},url:'http://en.wikipedia.org/wiki/Norman_H._Stahl', dutyStation:'Boston, MA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_First_Circuit', name:'Kermit Lipez', title:'Senior Judge', born:'1941',  court:'1st Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1998'},url:'http://en.wikipedia.org/wiki/Kermit_Lipez', dutyStation:'Portland, ME'}






    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Second_Circuit', name:'Robert Katzmann', title:'Chief Judge', born:'1953',  court:'2d Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1999'},url:'http://en.wikipedia.org/wiki/Robert_Katzmann', dutyStation:'New York, NY'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Second_Circuit', name:'Dennis G. Jacobs', title:'Circuit Judge', born:'1944',  court:'2d Cir.', nominatedBy:{name:'G.H.W. Bush', party:'R', year:'1992'},url:'http://en.wikipedia.org/wiki/Dennis_G._Jacobs', dutyStation:'New York, NY'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Second_Circuit', name:'José A. Cabranes', title:'Circuit Judge', born:'1940',  court:'2d Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1994'},url:'http://en.wikipedia.org/wiki/Jos%C3%A9_A._Cabranes', dutyStation:'New Haven, CT'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Second_Circuit', name:'Rosemary S. Pooler', title:'Circuit Judge', born:'1938',  court:'2d Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1998'},url:'http://en.wikipedia.org/wiki/Rosemary_S._Pooler', dutyStation:'Syracuse, NY'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Second_Circuit', name:'Reena Raggi', title:'Circuit Judge', born:'1951',  court:'2d Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2002'},url:'http://en.wikipedia.org/wiki/Reena_Raggi', dutyStation:'New York, NY'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Second_Circuit', name:'Richard C. Wesley', title:'Circuit Judge', born:'1949',  court:'2d Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2003'},url:'http://en.wikipedia.org/wiki/Richard_C._Wesley', dutyStation:'Geneseo, NY'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Second_Circuit', name:'Peter W. Hall', title:'Circuit Judge', born:'1948',  court:'2d Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2004'},url:'http://en.wikipedia.org/wiki/Peter_W._Hall', dutyStation:'Rutland, VT'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Second_Circuit', name:'Debra Ann Livingston', title:'Circuit Judge', born:'1959',  court:'2d Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2007'},url:'http://en.wikipedia.org/wiki/Debra_Ann_Livingston', dutyStation:'New York, NY'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Second_Circuit', name:'Gerard E. Lynch', title:'Circuit Judge', born:'1951',  court:'2d Cir.', nominatedBy:{name:'Obama', party:'D', year:'2009'},url:'http://en.wikipedia.org/wiki/Gerard_E._Lynch', dutyStation:'New York, NY'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Second_Circuit', name:'Denny Chin', title:'Circuit Judge', born:'1954',  court:'2d Cir.', nominatedBy:{name:'Obama', party:'D', year:'2010'},url:'http://en.wikipedia.org/wiki/Denny_Chin', dutyStation:'New York, NY'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Second_Circuit', name:'Raymond Lohier, Jr.', title:'Circuit Judge', born:'1965',  court:'2d Cir.', nominatedBy:{name:'Obama', party:'D', year:'2010'},url:'http://en.wikipedia.org/wiki/Raymond_Lohier,_Jr.', dutyStation:'New York, NY'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Second_Circuit', name:'Susan L. Carney', title:'Circuit Judge', born:'1951',  court:'2d Cir.', nominatedBy:{name:'Obama', party:'D', year:'2011'},url:'http://en.wikipedia.org/wiki/Susan_L._Carney', dutyStation:'New Haven, CT'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Second_Circuit', name:'Christopher F. Droney', title:'Circuit Judge', born:'1954',  court:'2d Cir.', nominatedBy:{name:'Obama', party:'D', year:'2011'},url:'http://en.wikipedia.org/wiki/Christopher_F._Droney', dutyStation:'Hartford, CT'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Second_Circuit', name:'Wilfred Feinberg', title:'Senior Judge', born:'1920',  court:'2d Cir.', nominatedBy:{name:'L. Johnson', party:'D', year:'1966'},url:'http://en.wikipedia.org/wiki/Wilfred_Feinberg', dutyStation:'inactive'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Second_Circuit', name:'Jon Ormond Newman', title:'Senior Judge', born:'1932',  court:'2d Cir.', nominatedBy:{name:'Carter', party:'D', year:'1979'},url:'http://en.wikipedia.org/wiki/Jon_Ormond_Newman', dutyStation:'Hartford, CT'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Second_Circuit', name:'Amalya Lyle Kearse', title:'Senior Judge', born:'1937',  court:'2d Cir.', nominatedBy:{name:'Carter', party:'D', year:'1979'},url:'http://en.wikipedia.org/wiki/Amalya_Lyle_Kearse', dutyStation:'New York, NY'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Second_Circuit', name:'Richard J. Cardamone', title:'Senior Judge', born:'1925',  court:'2d Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1981'},url:'http://en.wikipedia.org/wiki/Richard_J._Cardamone', dutyStation:'inactive'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Second_Circuit', name:'Ralph K. Winter, Jr.', title:'Senior Judge', born:'1935',  court:'2d Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1981'},url:'http://en.wikipedia.org/wiki/Ralph_K._Winter,_Jr.', dutyStation:'New Haven, CT'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Second_Circuit', name:'John M. Walker, Jr.', title:'Senior Judge', born:'1940',  court:'2d Cir.', nominatedBy:{name:'G.H.W. Bush', party:'R', year:'1989'},url:'http://en.wikipedia.org/wiki/John_M._Walker,_Jr.', dutyStation:'New Haven, CT'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Second_Circuit', name:'Pierre N. Leval', title:'Senior Judge', born:'1936',  court:'2d Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1993'},url:'http://en.wikipedia.org/wiki/Pierre_N._Leval', dutyStation:'New York, NY'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Second_Circuit', name:'Guido Calabresi', title:'Senior Judge', born:'1932',  court:'2d Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1994'},url:'http://en.wikipedia.org/wiki/Guido_Calabresi', dutyStation:'New Haven, CT'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Second_Circuit', name:'Chester J. Straub', title:'Senior Judge', born:'1937',  court:'2d Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1998'},url:'http://en.wikipedia.org/wiki/Chester_J._Straub', dutyStation:'New York, NY'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Second_Circuit', name:'Robert D. Sack', title:'Senior Judge', born:'1939',  court:'2d Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1998'},url:'http://en.wikipedia.org/wiki/Robert_D._Sack', dutyStation:'New York, NY'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Second_Circuit', name:'Barrington Daniels Parker, Jr.', title:'Senior Judge', born:'1944',  court:'2d Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2001'},url:'http://en.wikipedia.org/wiki/Barrington_Daniels_Parker,_Jr.', dutyStation:'New York, NY'}





    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Third_Circuit', name:'Theodore A. McKee', title:'Chief Judge', born:'1947',  court:'3rd Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1994'},url:'http://en.wikipedia.org/wiki/Theodore_A._McKee', dutyStation:'Philadelphia, PA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Third_Circuit', name:'Marjorie O. Rendell', title:'Circuit Judge', born:'1947',  court:'3rd Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1997'},url:'http://en.wikipedia.org/wiki/Marjorie_O._Rendell', dutyStation:'Philadelphia, PA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Third_Circuit', name:'Thomas L. Ambro', title:'Circuit Judge', born:'1949',  court:'3rd Cir.', nominatedBy:{name:'Clinton', party:'D', year:'2000'},url:'http://en.wikipedia.org/wiki/Thomas_L._Ambro', dutyStation:'Wilmington, DE'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Third_Circuit', name:'Julio M. Fuentes', title:'Circuit Judge', born:'1946',  court:'3rd Cir.', nominatedBy:{name:'Clinton', party:'D', year:'2000'},url:'http://en.wikipedia.org/wiki/Julio_M._Fuentes', dutyStation:'Newark, NJ'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Third_Circuit', name:'D. Brooks Smith', title:'Circuit Judge', born:'1951',  court:'3rd Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2002'},url:'http://en.wikipedia.org/wiki/D._Brooks_Smith', dutyStation:'Duncansville, PA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Third_Circuit', name:'D. Michael Fisher', title:'Circuit Judge', born:'1944',  court:'3rd Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2003'},url:'http://en.wikipedia.org/wiki/D._Michael_Fisher', dutyStation:'Pittsburgh, PA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Third_Circuit', name:'Michael Chagares', title:'Circuit Judge', born:'1962',  court:'3rd Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2006'},url:'http://en.wikipedia.org/wiki/Michael_Chagares', dutyStation:'Newark, NJ'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Third_Circuit', name:'Kent A. Jordan', title:'Circuit Judge', born:'1957',  court:'3rd Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2006'},url:'http://en.wikipedia.org/wiki/Kent_A._Jordan', dutyStation:'Wilmington, DE'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Third_Circuit', name:'Thomas M. Hardiman', title:'Circuit Judge', born:'1965',  court:'3rd Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2007'},url:'http://en.wikipedia.org/wiki/Thomas_M._Hardiman', dutyStation:'Pittsburgh, PA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Third_Circuit', name:'Joseph A. Greenaway', title:'Circuit Judge', born:'1957',  court:'3rd Cir.', nominatedBy:{name:'Obama', party:'D', year:'2010'},url:'http://en.wikipedia.org/wiki/Joseph_A._Greenaway,_Jr.', dutyStation:'Newark, NJ'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Third_Circuit', name:'Thomas I. Vanaskie', title:'Circuit Judge', born:'1953',  court:'3rd Cir.', nominatedBy:{name:'Obama', party:'D', year:'2010'},url:'http://en.wikipedia.org/wiki/Thomas_I._Vanaskie', dutyStation:'Scranton, PA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Third_Circuit', name:'Patty Shwartz', title:'Circuit Judge', born:'1961',  court:'3rd Cir.', nominatedBy:{name:'Obama', party:'D', year:'2013'},url:'http://en.wikipedia.org/wiki/Patty_Shwartz', dutyStation:'Newark, NJ'}


    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Third_Circuit', name:'Ruggero J. Aldisert', title:'Senior Judge', born:'1919',  court:'3rd Cir.', nominatedBy:{name:'L. Johnson', party:'D', year:'1968'},url:'http://en.wikipedia.org/wiki/Ruggero_J._Aldisert', dutyStation:'Santa Barbara, CA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Third_Circuit', name:'Leonard I. Garth', title:'Senior Judge', born:'1921',  court:'3rd Cir.', nominatedBy:{name:'Nixon', party:'R', year:'1973'},url:'http://en.wikipedia.org/wiki/Leonard_I._Garth', dutyStation:'Newark, NJ'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Third_Circuit', name:'Dolores Korman Sloviter', title:'Senior Judge', born:'1932',  court:'3rd Cir.', nominatedBy:{name:'Carter', party:'D', year:'1979'},url:'http://en.wikipedia.org/wiki/Dolores_Sloviter', dutyStation:'Philadelphia, PA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Third_Circuit', name:'Walter King Stapleton', title:'Senior Judge', born:'1934',  court:'3rd Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1985'},url:'http://en.wikipedia.org/wiki/Walter_King_Stapleton', dutyStation:'Wilmington, DE'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Third_Circuit', name:'Morton Ira Greenberg', title:'Senior Judge', born:'1933',  court:'3rd Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1987'},url:'http://en.wikipedia.org/wiki/Morton_Ira_Greenberg', dutyStation:'Trenton, NJ'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Third_Circuit', name:'Anthony Joseph Scirica', title:'Senior Judge', born:'1940',  court:'3rd Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1987'},url:'http://en.wikipedia.org/wiki/Anthony_Joseph_Scirica', dutyStation:'Philadelphia, PA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Third_Circuit', name:'Robert E. Cowen', title:'Senior Judge', born:'1930',  court:'3rd Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1987'},url:'http://en.wikipedia.org/wiki/Robert_Cowen', dutyStation:'Trenton, NJ'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Third_Circuit', name:'Richard Lowell Nygaard', title:'Senior Judge', born:'1940',  court:'3rd Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1988'},url:'http://en.wikipedia.org/wiki/Richard_Lowell_Nygaard', dutyStation:'Erie, PA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Third_Circuit', name:'Jane Richards Roth', title:'Senior Judge', born:'1935',  court:'3rd Cir.', nominatedBy:{name:'G.H.W. Bush', party:'R', year:'1991'},url:'http://en.wikipedia.org/wiki/Jane_Richards_Roth', dutyStation:'Washington, DC'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Third_Circuit', name:'Maryanne Trump Barry', title:'Senior Judge', born:'1937',  court:'3rd Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1999'},url:'http://en.wikipedia.org/wiki/Maryanne_Trump_Barry', dutyStation:'Newark, NJ'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Third_Circuit', name:'Franklin Stuart Van Antwerpen', title:'Senior Judge', born:'1941',  court:'3rd Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2004'},url:'http://en.wikipedia.org/wiki/Franklin_Stuart_Van_Antwerpen', dutyStation:'Easton, PA'}




    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Fourth_Circuit', name:'William Byrd Traxler, Jr.', title:'Chief Judge', born:'1948',  court:'4th Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1998'},url:'http://en.wikipedia.org/wiki/William_Byrd_Traxler,_Jr.', dutyStation:'Greenville, SC'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Fourth_Circuit', name:'J. Harvie Wilkinson III', title:'Circuit Judge', born:'1944',  court:'4th Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1984'},url:'http://en.wikipedia.org/wiki/J._Harvie_Wilkinson_III', dutyStation:'Charlottesville, VA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Fourth_Circuit', name:'Paul V. Niemeyer', title:'Circuit Judge', born:'1941',  court:'4th Cir.', nominatedBy:{name:'G.H.W. Bush', party:'R', year:'1990'},url:'http://en.wikipedia.org/wiki/Paul_V._Niemeyer', dutyStation:'Baltimore, MD'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Fourth_Circuit', name:'Diana Gribbon Motz', title:'Circuit Judge', born:'1943',  court:'4th Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1994'},url:'http://en.wikipedia.org/wiki/Diana_Gribbon_Motz', dutyStation:'Baltimore, MD'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Fourth_Circuit', name:'Robert Bruce King', title:'Circuit Judge', born:'1940',  court:'4th Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1998'},url:'http://en.wikipedia.org/wiki/Robert_Bruce_King', dutyStation:'Charleston, WV'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Fourth_Circuit', name:'Roger Gregory', title:'Circuit Judge', born:'1953',  court:'4th Cir.', nominatedBy:{name:'Clinton/G.W. Bush[Note 1]', party:'D', year:'2000'},url:'http://en.wikipedia.org/wiki/Roger_Gregory', dutyStation:'Richmond, VA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Fourth_Circuit', name:'Dennis Shedd', title:'Circuit Judge', born:'1953',  court:'4th Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2002'},url:'http://en.wikipedia.org/wiki/Dennis_Shedd', dutyStation:'Columbia, SC'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Fourth_Circuit', name:'Allyson Kay Duncan', title:'Circuit Judge', born:'1951',  court:'4th Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2003'},url:'http://en.wikipedia.org/wiki/Allyson_Kay_Duncan', dutyStation:'Raleigh, NC'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Fourth_Circuit', name:'G. Steven Agee', title:'Circuit Judge', born:'1952',  court:'4th Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2008'},url:'http://en.wikipedia.org/wiki/G._Steven_Agee', dutyStation:'Salem, VA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Fourth_Circuit', name:'Barbara Milano Keenan', title:'Circuit Judge', born:'1950',  court:'4th Cir.', nominatedBy:{name:'Obama', party:'D', year:'2010'},url:'http://en.wikipedia.org/wiki/Barbara_Milano_Keenan', dutyStation:'Alexandria, VA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Fourth_Circuit', name:'James A. Wynn, Jr.', title:'Circuit Judge', born:'1954',  court:'4th Cir.', nominatedBy:{name:'Obama', party:'D', year:'2010'},url:'http://en.wikipedia.org/wiki/James_A._Wynn,_Jr.', dutyStation:'Raleigh, NC'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Fourth_Circuit', name:'Albert Diaz', title:'Circuit Judge', born:'1960',  court:'4th Cir.', nominatedBy:{name:'Obama', party:'D', year:'2010'},url:'http://en.wikipedia.org/wiki/Albert_Diaz_(judge)', dutyStation:'Charlotte, NC'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Fourth_Circuit', name:'Henry Franklin Floyd', title:'Circuit Judge', born:'1947',  court:'4th Cir.', nominatedBy:{name:'Obama', party:'D', year:'2011'},url:'http://en.wikipedia.org/wiki/Henry_Franklin_Floyd', dutyStation:'Pickens, SC'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Fourth_Circuit', name:'Stephanie Thacker', title:'Circuit Judge', born:'1965',  court:'4th Cir.', nominatedBy:{name:'Obama', party:'D', year:'2012'},url:'http://en.wikipedia.org/wiki/Stephanie_Thacker', dutyStation:'Charleston, WV'}

    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Fourth_Circuit', name:'James Dickson Phillips, Jr.', title:'Senior Judge', born:'1922',  court:'4th Cir.', nominatedBy:{name:'Carter', party:'D', year:'1978'},url:'http://en.wikipedia.org/wiki/James_Dickson_Phillips,_Jr.', dutyStation:'inactive'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Fourth_Circuit', name:'Robert F. Chapman', title:'Senior Judge', born:'1926',  court:'4th Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1981'},url:'http://en.wikipedia.org/wiki/Robert_F._Chapman', dutyStation:'inactive'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Fourth_Circuit', name:'Clyde H. Hamilton', title:'Senior Judge', born:'1934',  court:'4th Cir.', nominatedBy:{name:'G.H.W. Bush', party:'R', year:'1991'},url:'http://en.wikipedia.org/wiki/Clyde_H._Hamilton', dutyStation:'Columbia, SC'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Fourth_Circuit', name:'Andre M. Davis', title:'Senior Judge', born:'1949',  court:'4th Cir.', nominatedBy:{name:'Obama', party:'D', year:'2009'},url:'http://en.wikipedia.org/wiki/Andre_M._Davis', dutyStation:'Baltimore, MD'}




    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Fifth_Circuit', name:'Carl E. Stewart', title:'Chief Judge', born:'1950',  court:'5th Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1994'},url:'http://en.wikipedia.org/wiki/Carl_E._Stewart', dutyStation:'Shreveport, LA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Fifth_Circuit', name:'E. Grady Jolly', title:'Circuit Judge', born:'1937',  court:'5th Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1982'},url:'http://en.wikipedia.org/wiki/E._Grady_Jolly', dutyStation:'Jackson, MS'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Fifth_Circuit', name:'W. Eugene Davis', title:'Circuit Judge', born:'1936',  court:'5th Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1983'},url:'http://en.wikipedia.org/wiki/W._Eugene_Davis', dutyStation:'Lafayette, LA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Fifth_Circuit', name:'Edith H. Jones', title:'Circuit Judge', born:'1949',  court:'5th Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1985'},url:'http://en.wikipedia.org/wiki/Edith_Jones', dutyStation:'Houston, TX'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Fifth_Circuit', name:'Jerry Edwin Smith', title:'Circuit Judge', born:'1946',  court:'5th Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1987'},url:'http://en.wikipedia.org/wiki/Jerry_Edwin_Smith', dutyStation:'Houston, TX'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Fifth_Circuit', name:'James L. Dennis', title:'Circuit Judge', born:'1936',  court:'5th Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1995'},url:'http://en.wikipedia.org/wiki/James_L._Dennis', dutyStation:'New Orleans, LA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Fifth_Circuit', name:'Edith Brown Clement', title:'Circuit Judge', born:'1948',  court:'5th Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2001'},url:'http://en.wikipedia.org/wiki/Edith_Brown_Clement', dutyStation:'New Orleans, LA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Fifth_Circuit', name:'Edward C. Prado', title:'Circuit Judge', born:'1947',  court:'5th Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2003'},url:'http://en.wikipedia.org/wiki/Edward_C._Prado', dutyStation:'San Antonio, TX'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Fifth_Circuit', name:'Priscilla Owen', title:'Circuit Judge', born:'1954',  court:'5th Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2005'},url:'http://en.wikipedia.org/wiki/Priscilla_Owen', dutyStation:'Austin, TX'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Fifth_Circuit', name:'Jennifer Walker Elrod', title:'Circuit Judge', born:'1966',  court:'5th Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2007'},url:'http://en.wikipedia.org/wiki/Jennifer_Elrod', dutyStation:'Houston, TX'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Fifth_Circuit', name:'Leslie H. Southwick', title:'Circuit Judge', born:'1950',  court:'5th Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2007'},url:'http://en.wikipedia.org/wiki/Leslie_H._Southwick', dutyStation:'Jackson, MS'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Fifth_Circuit', name:'Catharina Haynes', title:'Circuit Judge', born:'1963',  court:'5th Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2008'},url:'http://en.wikipedia.org/wiki/Catharina_Haynes', dutyStation:'Dallas, TX'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Fifth_Circuit', name:'James E. Graves, Jr.', title:'Circuit Judge', born:'1953',  court:'5th Cir.', nominatedBy:{name:'Obama', party:'D', year:'2011'},url:'http://en.wikipedia.org/wiki/James_E._Graves,_Jr.', dutyStation:'Jackson, MS'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Fifth_Circuit', name:'Stephen A. Higginson', title:'Circuit Judge', born:'1961',  court:'5th Cir.', nominatedBy:{name:'Obama', party:'D', year:'2011'},url:'http://en.wikipedia.org/wiki/Stephen_A._Higginson', dutyStation:'New Orleans, LA'}



    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Fifth_Circuit', name:'Carolyn Dineen King', title:'Senior Judge', born:'1938',  court:'5th Cir.', nominatedBy:{name:'Carter', party:'D', year:'1979'},url:'http://en.wikipedia.org/wiki/Carolyn_Dineen_King', dutyStation:'Houston, TX'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Fifth_Circuit', name:'Thomas Morrow Reavley', title:'Senior Judge', born:'1921',  court:'5th Cir.', nominatedBy:{name:'Carter', party:'D', year:'1979'},url:'http://en.wikipedia.org/wiki/Thomas_Morrow_Reavley', dutyStation:'Houston, TX'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Fifth_Circuit', name:'Patrick Higginbotham', title:'Senior Judge', born:'1938',  court:'5th Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1982'},url:'http://en.wikipedia.org/wiki/Patrick_Higginbotham', dutyStation:'Austin, TX'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Fifth_Circuit', name:'Rhesa Hawkins Barksdale', title:'Senior Judge', born:'1944',  court:'5th Cir.', nominatedBy:{name:'G.H.W. Bush', party:'R', year:'1990'},url:'http://en.wikipedia.org/wiki/Rhesa_Hawkins_Barksdale', dutyStation:'Jackson, MS'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Fifth_Circuit', name:'Jacques L. Wiener, Jr.', title:'Senior Judge', born:'1934',  court:'5th Cir.', nominatedBy:{name:'G.H.W. Bush', party:'R', year:'1990'},url:'http://en.wikipedia.org/wiki/Jacques_L._Wiener,_Jr.', dutyStation:'New Orleans, LA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Fifth_Circuit', name:'Emilio M. Garza', title:'Senior Judge', born:'1947',  court:'5th Cir.', nominatedBy:{name:'G.H.W. Bush', party:'R', year:'1991'},url:'http://en.wikipedia.org/wiki/Emilio_M._Garza', dutyStation:'San Antonio, TX'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Fifth_Circuit', name:'Harold R. DeMoss, Jr.', title:'Senior Judge', born:'1930',  court:'5th Cir.', nominatedBy:{name:'G.H.W. Bush', party:'R', year:'1991'},url:'http://en.wikipedia.org/wiki/Harold_R._DeMoss,_Jr.', dutyStation:'Houston, TX'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Fifth_Circuit', name:'Fortunato "Pete" Benavides', title:'Senior Judge', born:'1947',  court:'5th Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1994'},url:'http://en.wikipedia.org/wiki/Fortunato_Benavides', dutyStation:'Austin, TX'}





    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Sixth_Circuit', name:'Alice M. Batchelder', title:'Chief Judge', born:'1944',  court:'6th Cir.', nominatedBy:{name:'G.H.W. Bush', party:'R', year:'1991'},url:'http://en.wikipedia.org/wiki/Alice_M._Batchelder', dutyStation:'Medina, OH'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Sixth_Circuit', name:'Danny Julian Boggs', title:'Circuit Judge', born:'1944',  court:'6th Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1986'},url:'http://en.wikipedia.org/wiki/Danny_Julian_Boggs', dutyStation:'Louisville, KY'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Sixth_Circuit', name:'Karen Nelson Moore', title:'Circuit Judge', born:'1948',  court:'6th Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1995'},url:'http://en.wikipedia.org/wiki/Karen_Nelson_Moore', dutyStation:'Cleveland, OH'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Sixth_Circuit', name:'R. Guy Cole, Jr.', title:'Circuit Judge', born:'1951',  court:'6th Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1995'},url:'http://en.wikipedia.org/wiki/R._Guy_Cole,_Jr.', dutyStation:'Columbus, OH'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Sixth_Circuit', name:'Eric L. Clay', title:'Circuit Judge', born:'1948',  court:'6th Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1997'},url:'http://en.wikipedia.org/wiki/Eric_L._Clay', dutyStation:'Detroit, MI'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Sixth_Circuit', name:'Julia Smith Gibbons', title:'Circuit Judge', born:'1950',  court:'6th Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2002'},url:'http://en.wikipedia.org/wiki/Julia_Smith_Gibbons', dutyStation:'Memphis, TN'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Sixth_Circuit', name:'John M. Rogers', title:'Circuit Judge', born:'1948',  court:'6th Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2002'},url:'http://en.wikipedia.org/wiki/John_M._Rogers', dutyStation:'Lexington, KY'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Sixth_Circuit', name:'Jeffrey Sutton', title:'Circuit Judge', born:'1960',  court:'6th Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2003'},url:'http://en.wikipedia.org/wiki/Jeffrey_Sutton', dutyStation:'Columbus, OH'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Sixth_Circuit', name:'Deborah L. Cook', title:'Circuit Judge', born:'1952',  court:'6th Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2003'},url:'http://en.wikipedia.org/wiki/Deborah_L._Cook', dutyStation:'Akron, OH'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Sixth_Circuit', name:'David McKeague', title:'Circuit Judge', born:'1946',  court:'6th Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2005'},url:'http://en.wikipedia.org/wiki/David_McKeague', dutyStation:'Lansing, MI'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Sixth_Circuit', name:'Richard Allen Griffin', title:'Circuit Judge', born:'1952',  court:'6th Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2005'},url:'http://en.wikipedia.org/wiki/Richard_Allen_Griffin', dutyStation:'Traverse City, MI'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Sixth_Circuit', name:'Raymond M. Kethledge', title:'Circuit Judge', born:'1966',  court:'6th Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2008'},url:'http://en.wikipedia.org/wiki/Raymond_Kethledge', dutyStation:'Ann Arbor, MI'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Sixth_Circuit', name:'Helene N. White', title:'Circuit Judge', born:'1954',  court:'6th Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2008'},url:'http://en.wikipedia.org/wiki/Helene_White', dutyStation:'Detroit, MI'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Sixth_Circuit', name:'Jane Branstetter Stranch', title:'Circuit Judge', born:'1953',  court:'6th Cir.', nominatedBy:{name:'Obama', party:'D', year:'2010'},url:'http://en.wikipedia.org/wiki/Jane_Branstetter_Stranch', dutyStation:'Nashville, TN'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Sixth_Circuit', name:'Bernice B. Donald', title:'Circuit Judge', born:'1951',  court:'6th Cir.', nominatedBy:{name:'Obama', party:'D', year:'2011'},url:'http://en.wikipedia.org/wiki/Bernice_B._Donald', dutyStation:'Memphis, TN'}

    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Sixth_Circuit', name:'Pierce Lively', title:'Senior Judge', born:'1921',  court:'6th Cir.', nominatedBy:{name:'Nixon', party:'R', year:'1972'},url:'http://en.wikipedia.org/wiki/Pierce_Lively', dutyStation:'inactive'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Sixth_Circuit', name:'Damon J. Keith', title:'Senior Judge', born:'1922',  court:'6th Cir.', nominatedBy:{name:'Carter', party:'D', year:'1977'},url:'http://en.wikipedia.org/wiki/Damon_J._Keith', dutyStation:'Detroit, MI'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Sixth_Circuit', name:'Gilbert Stroud Merritt, Jr.', title:'Senior Judge', born:'1936',  court:'6th Cir.', nominatedBy:{name:'Carter', party:'D', year:'1977'},url:'http://en.wikipedia.org/wiki/Gilbert_Stroud_Merritt,_Jr.', dutyStation:'Nashville, TN'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Sixth_Circuit', name:'Harry W. Wellford', title:'Senior Judge', born:'1924',  court:'6th Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1982'},url:'http://en.wikipedia.org/wiki/Harry_W._Wellford', dutyStation:'inactive'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Sixth_Circuit', name:'Herbert Theodore Milburn', title:'Senior Judge', born:'1931',  court:'6th Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1984'},url:'http://en.wikipedia.org/wiki/Herbert_Theodore_Milburn', dutyStation:'inactive'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Sixth_Circuit', name:'Ralph B. Guy, Jr.', title:'Senior Judge', born:'1929',  court:'6th Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1985'},url:'http://en.wikipedia.org/wiki/Ralph_B._Guy,_Jr.', dutyStation:'Ann Arbor, MI'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Sixth_Circuit', name:'James Leo Ryan', title:'Senior Judge', born:'1932',  court:'6th Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1985'},url:'http://en.wikipedia.org/wiki/James_Leo_Ryan', dutyStation:'inactive'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Sixth_Circuit', name:'Alan Eugene Norris', title:'Senior Judge', born:'1935',  court:'6th Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1986'},url:'http://en.wikipedia.org/wiki/Alan_Eugene_Norris', dutyStation:'Columbus, OH'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Sixth_Circuit', name:'Richard Fred Suhrheinrich', title:'Senior Judge', born:'1936',  court:'6th Cir.', nominatedBy:{name:'G.H.W. Bush', party:'R', year:'1990'},url:'http://en.wikipedia.org/wiki/Richard_Fred_Suhrheinrich', dutyStation:'Lansing, MI'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Sixth_Circuit', name:'Eugene Edward Siler, Jr.', title:'Senior Judge', born:'1936',  court:'6th Cir.', nominatedBy:{name:'G.H.W. Bush', party:'R', year:'1991'},url:'http://en.wikipedia.org/wiki/Eugene_Edward_Siler,_Jr.', dutyStation:'London, KY'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Sixth_Circuit', name:'Martha Craig Daughtrey', title:'Senior Judge', born:'1942',  court:'6th Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1993'},url:'http://en.wikipedia.org/wiki/Martha_Craig_Daughtrey', dutyStation:'Nashville, TN'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Sixth_Circuit', name:'Ronald Lee Gilman', title:'Senior Judge', born:'1942',  court:'6th Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1997'},url:'http://en.wikipedia.org/wiki/Ronald_Lee_Gilman', dutyStation:'Memphis, TN'}




    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Seventh_Circuit', name:'Diane Pamela Wood', title:'Chief Judge', born:'1950',  court:'7th Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1995'},url:'http://en.wikipedia.org/wiki/Diane_Pamela_Wood', dutyStation:'Chicago, IL'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Seventh_Circuit', name:'Richard Posner', title:'Circuit Judge', born:'1939',  court:'7th Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1981'},url:'http://en.wikipedia.org/wiki/Richard_Posner', dutyStation:'Chicago, IL'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Seventh_Circuit', name:'Joel Martin Flaum', title:'Circuit Judge', born:'1936',  court:'7th Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1983'},url:'http://en.wikipedia.org/wiki/Joel_Martin_Flaum', dutyStation:'Chicago, IL'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Seventh_Circuit', name:'Frank H. Easterbrook', title:'Circuit Judge', born:'1948',  court:'7th Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1985'},url:'http://en.wikipedia.org/wiki/Frank_H._Easterbrook', dutyStation:'Chicago, IL'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Seventh_Circuit', name:'Michael Stephen Kanne', title:'Circuit Judge', born:'1938',  court:'7th Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1987'},url:'http://en.wikipedia.org/wiki/Michael_Stephen_Kanne', dutyStation:'Lafayette, IN'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Seventh_Circuit', name:'Ilana Rovner', title:'Circuit Judge', born:'1938',  court:'7th Cir.', nominatedBy:{name:'G.H.W. Bush', party:'R', year:'1992'},url:'http://en.wikipedia.org/wiki/Ilana_Rovner', dutyStation:'Chicago, IL'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Seventh_Circuit', name:'Ann Claire Williams', title:'Circuit Judge', born:'1949',  court:'7th Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1999'},url:'http://en.wikipedia.org/wiki/Ann_Claire_Williams', dutyStation:'Chicago, IL'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Seventh_Circuit', name:'Diane S. Sykes', title:'Circuit Judge', born:'1957',  court:'7th Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2004'},url:'http://en.wikipedia.org/wiki/Diane_S._Sykes', dutyStation:'Milwaukee, WI'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Seventh_Circuit', name:'John Daniel Tinder', title:'Circuit Judge', born:'1950',  court:'7th Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2007'},url:'http://en.wikipedia.org/wiki/John_Daniel_Tinder', dutyStation:'Indianapolis, IN'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Seventh_Circuit', name:'David F. Hamilton', title:'Circuit Judge', born:'1957',  court:'7th Cir.', nominatedBy:{name:'Obama', party:'D', year:'2009'},url:'http://en.wikipedia.org/wiki/David_F._Hamilton', dutyStation:'Bloomington, IN'}

    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Seventh_Circuit', name:'William Joseph Bauer', title:'Senior Judge', born:'1926',  court:'7th Cir.', nominatedBy:{name:'Ford', party:'R', year:'1974'},url:'http://en.wikipedia.org/wiki/William_Joseph_Bauer', dutyStation:'Chicago, IL'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Seventh_Circuit', name:'Richard Dickson Cudahy', title:'Senior Judge', born:'1926',  court:'7th Cir.', nominatedBy:{name:'Carter', party:'D', year:'1979'},url:'http://en.wikipedia.org/wiki/Richard_Dickson_Cudahy', dutyStation:'Chicago, IL'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Seventh_Circuit', name:'Kenneth Francis Ripple', title:'Senior Judge', born:'1943',  court:'7th Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1985'},url:'http://en.wikipedia.org/wiki/Kenneth_Francis_Ripple', dutyStation:'South Bend, IN'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Seventh_Circuit', name:'Daniel Anthony Manion', title:'Senior Judge', born:'1942',  court:'7th Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1986'},url:'http://en.wikipedia.org/wiki/Daniel_Anthony_Manion', dutyStation:'South Bend, IN'}





    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Eighth_Circuit', name:'William J. Riley', title:'Chief Judge', born:'1947',  court:'8th Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2001'},url:'http://en.wikipedia.org/wiki/William_J._Riley', dutyStation:'Omaha, NE'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Eighth_Circuit', name:'Roger Leland Wollman', title:'Circuit Judge', born:'1934',  court:'8th Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1985'},url:'http://en.wikipedia.org/wiki/Roger_Leland_Wollman', dutyStation:'Sioux Falls, SD'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Eighth_Circuit', name:'James B. Loken', title:'Circuit Judge', born:'1940',  court:'8th Cir.', nominatedBy:{name:'G.H.W. Bush', party:'R', year:'1990'},url:'http://en.wikipedia.org/wiki/James_B._Loken', dutyStation:'Minneapolis, MN'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Eighth_Circuit', name:'Diana E. Murphy', title:'Circuit Judge', born:'1934',  court:'8th Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1994'},url:'http://en.wikipedia.org/wiki/Diana_E._Murphy', dutyStation:'Minneapolis, MN'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Eighth_Circuit', name:'Kermit Edward Bye', title:'Circuit Judge', born:'1937',  court:'8th Cir.', nominatedBy:{name:'Clinton', party:'D', year:'2000'},url:'http://en.wikipedia.org/wiki/Kermit_Edward_Bye', dutyStation:'Fargo, ND'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Eighth_Circuit', name:'Lavenski R. Smith', title:'Circuit Judge', born:'1958',  court:'8th Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2002'},url:'http://en.wikipedia.org/wiki/Lavenski_R._Smith', dutyStation:'Little Rock, AR'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Eighth_Circuit', name:'Steven M. Colloton', title:'Circuit Judge', born:'1963',  court:'8th Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2003'},url:'http://en.wikipedia.org/wiki/Steven_M._Colloton', dutyStation:'Des Moines, IA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Eighth_Circuit', name:'Raymond W. Gruender', title:'Circuit Judge', born:'1963',  court:'8th Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2004'},url:'http://en.wikipedia.org/wiki/Raymond_W._Gruender', dutyStation:'Saint Louis, MO'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Eighth_Circuit', name:'William Duane Benton', title:'Circuit Judge', born:'1950',  court:'8th Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2004'},url:'http://en.wikipedia.org/wiki/William_Duane_Benton', dutyStation:'Kansas City, MO'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Eighth_Circuit', name:'Bobby E. Shepherd', title:'Circuit Judge', born:'1951',  court:'8th Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2006'},url:'http://en.wikipedia.org/wiki/Bobby_E._Shepherd', dutyStation:'El Dorado, AR'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Eighth_Circuit', name:'Jane Louise Kelly', title:'Circuit Judge', born:'1964',  court:'8th Cir.', nominatedBy:{name:'Obama', party:'D', year:'2013'},url:'http://en.wikipedia.org/wiki/Jane_Louise_Kelly', dutyStation:'Cedar Rapids, IA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Eighth_Circuit', name:'Myron H. Bright', title:'Senior Judge', born:'1919',  court:'8th Cir.', nominatedBy:{name:'L. Johnson', party:'D', year:'1968'},url:'http://en.wikipedia.org/wiki/Myron_H._Bright', dutyStation:'Fargo, ND'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Eighth_Circuit', name:'George Gardner Fagg', title:'Senior Judge', born:'1934',  court:'8th Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1982'},url:'http://en.wikipedia.org/wiki/George_Gardner_Fagg', dutyStation:'inactive'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Eighth_Circuit', name:'Pasco Bowman II', title:'Senior Judge', born:'1933',  court:'8th Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1983'},url:'http://en.wikipedia.org/wiki/Pasco_Bowman_II', dutyStation:'Kansas City, MO'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Eighth_Circuit', name:'C. Arlen Beam', title:'Senior Judge', born:'1930',  court:'8th Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1987'},url:'http://en.wikipedia.org/wiki/C._Arlen_Beam', dutyStation:'Lincoln, NE'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Eighth_Circuit', name:'David R. Hansen', title:'Senior Judge', born:'1938',  court:'8th Cir.', nominatedBy:{name:'G.H.W. Bush', party:'R', year:'1991'},url:'http://en.wikipedia.org/wiki/David_R._Hansen', dutyStation:'inactive'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Eighth_Circuit', name:'Morris Sheppard Arnold', title:'Senior Judge', born:'1941',  court:'8th Cir.', nominatedBy:{name:'G.H.W. Bush', party:'R', year:'1992'},url:'http://en.wikipedia.org/wiki/Morris_Sheppard_Arnold', dutyStation:'Little Rock, AR'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Eighth_Circuit', name:'Michael Joseph Melloy', title:'Senior Judge', born:'1948',  court:'8th Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2002'},url:'http://en.wikipedia.org/wiki/Michael_Joseph_Melloy', dutyStation:'Cedar Rapids, IA'}





    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'Alex Kozinski', title:'Chief Judge', born:'1950',  court:'9th Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1985'},url:'http://en.wikipedia.org/wiki/Alex_Kozinski', dutyStation:'Pasadena, CA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'Harry Pregerson', title:'Circuit Judge', born:'1923',  court:'9th Cir.', nominatedBy:{name:'Carter', party:'D', year:'1979'},url:'http://en.wikipedia.org/wiki/Harry_Pregerson', dutyStation:'Woodland Hills, CA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'Stephen Reinhardt', title:'Circuit Judge', born:'1931',  court:'9th Cir.', nominatedBy:{name:'Carter', party:'D', year:'1980'},url:'http://en.wikipedia.org/wiki/Stephen_Reinhardt', dutyStation:'Los Angeles, CA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'Diarmuid Fionntain O\'Scannlain', title:'Circuit Judge', born:'1937',  court:'9th Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1986'},url:'http://en.wikipedia.org/wiki/Diarmuid_Fionntain_O%27Scannlain', dutyStation:'Portland, OR'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'Sidney Runyan Thomas', title:'Circuit Judge', born:'1953',  court:'9th Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1996'},url:'http://en.wikipedia.org/wiki/Sidney_Runyan_Thomas', dutyStation:'Billings, MT'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'Barry G. Silverman', title:'Circuit Judge', born:'1951',  court:'9th Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1998'},url:'http://en.wikipedia.org/wiki/Barry_G._Silverman', dutyStation:'Phoenix, AZ'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'Susan P. Graber', title:'Circuit Judge', born:'1949',  court:'9th Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1998'},url:'http://en.wikipedia.org/wiki/Susan_P._Graber', dutyStation:'Portland, OR'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'M. Margaret McKeown', title:'Circuit Judge', born:'1951',  court:'9th Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1998'},url:'http://en.wikipedia.org/wiki/M._Margaret_McKeown', dutyStation:'San Diego, CA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'Kim McLane Wardlaw', title:'Circuit Judge', born:'1954',  court:'9th Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1998'},url:'http://en.wikipedia.org/wiki/Kim_McLane_Wardlaw', dutyStation:'Pasadena, CA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'William A. Fletcher', title:'Circuit Judge', born:'1945',  court:'9th Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1998'},url:'http://en.wikipedia.org/wiki/William_A._Fletcher', dutyStation:'San Francisco, CA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'Ronald M. Gould', title:'Circuit Judge', born:'1946',  court:'9th Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1999'},url:'http://en.wikipedia.org/wiki/Ronald_M._Gould', dutyStation:'Seattle, WA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'Richard A. Paez', title:'Circuit Judge', born:'1947',  court:'9th Cir.', nominatedBy:{name:'Clinton', party:'D', year:'2000'},url:'http://en.wikipedia.org/wiki/Richard_Paez', dutyStation:'Pasadena, CA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'Marsha S. Berzon', title:'Circuit Judge', born:'1945',  court:'9th Cir.', nominatedBy:{name:'Clinton', party:'D', year:'2000'},url:'http://en.wikipedia.org/wiki/Marsha_S._Berzon', dutyStation:'San Francisco, CA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'Richard C. Tallman', title:'Circuit Judge', born:'1953',  court:'9th Cir.', nominatedBy:{name:'Clinton', party:'D', year:'2000'},url:'http://en.wikipedia.org/wiki/Richard_C._Tallman', dutyStation:'Seattle, WA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'Johnnie B. Rawlinson', title:'Circuit Judge', born:'1952',  court:'9th Cir.', nominatedBy:{name:'Clinton', party:'D', year:'2000'},url:'http://en.wikipedia.org/wiki/Johnnie_B._Rawlinson', dutyStation:'Las Vegas, NV'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'Richard R. Clifton', title:'Circuit Judge', born:'1950',  court:'9th Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2002'},url:'http://en.wikipedia.org/wiki/Richard_R._Clifton', dutyStation:'Honolulu, HI'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'Jay Bybee', title:'Circuit Judge', born:'1953',  court:'9th Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2003'},url:'http://en.wikipedia.org/wiki/Jay_Bybee', dutyStation:'Las Vegas, NV'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'Consuelo Maria Callahan', title:'Circuit Judge', born:'1950',  court:'9th Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2003'},url:'http://en.wikipedia.org/wiki/Consuelo_Maria_Callahan', dutyStation:'Sacramento, CA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'Carlos T. Bea', title:'Circuit Judge', born:'1934',  court:'9th Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2003'},url:'http://en.wikipedia.org/wiki/Carlos_T._Bea', dutyStation:'San Francisco, CA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'Milan D. Smith, Jr.', title:'Circuit Judge', born:'1942',  court:'9th Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2006'},url:'http://en.wikipedia.org/wiki/Milan_Smith', dutyStation:'El Segundo, CA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'Sandra Segal Ikuta', title:'Circuit Judge', born:'1954',  court:'9th Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2006'},url:'http://en.wikipedia.org/wiki/Sandra_Segal_Ikuta', dutyStation:'Pasadena, CA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'N. Randy Smith', title:'Circuit Judge', born:'1949',  court:'9th Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2007'},url:'http://en.wikipedia.org/wiki/Norman_Randy_Smith', dutyStation:'Pocatello, ID'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'Mary H. Murguia', title:'Circuit Judge', born:'1960',  court:'9th Cir.', nominatedBy:{name:'Obama', party:'D', year:'2011'},url:'http://en.wikipedia.org/wiki/Mary_H._Murguia', dutyStation:'Phoenix, AZ'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'Morgan Christen', title:'Circuit Judge', born:'1961',  court:'9th Cir.', nominatedBy:{name:'Obama', party:'D', year:'2012'},url:'http://en.wikipedia.org/wiki/Morgan_Christen', dutyStation:'Anchorage, AK'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'Jacqueline Nguyen', title:'Circuit Judge', born:'1965',  court:'9th Cir.', nominatedBy:{name:'Obama', party:'D', year:'2012'},url:'http://en.wikipedia.org/wiki/Jacqueline_Nguyen', dutyStation:'Pasadena, CA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'Paul J. Watford', title:'Circuit Judge', born:'1967',  court:'9th Cir.', nominatedBy:{name:'Obama', party:'D', year:'2012'},url:'http://en.wikipedia.org/wiki/Paul_J._Watford', dutyStation:'Pasadena, CA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'Andrew D. Hurwitz', title:'Circuit Judge', born:'1947',  court:'9th Cir.', nominatedBy:{name:'Obama', party:'D', year:'2012'},url:'http://en.wikipedia.org/wiki/Andrew_D._Hurwitz', dutyStation:'Phoenix, AZ'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'John B. Owens', title:'Circuit Judge', born:'1971',  court:'9th Cir.', nominatedBy:{name:'Obama', party:'D', year:'2014'},url:'http://en.wikipedia.org/wiki/John_B._Owens', dutyStation:'San Diego, CA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'Michelle T. Friedland', title:'Circuit Judge', born:'1972',  court:'9th Cir.', nominatedBy:{name:'Obama', party:'D', year:'2014'},url:'http://en.wikipedia.org/wiki/Michelle_T._Friedland', dutyStation:'San Francisco, CA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'Alfred Theodore Goodwin', title:'Senior Judge', born:'1923',  court:'9th Cir.', nominatedBy:{name:'Nixon', party:'R', year:'1971'},url:'http://en.wikipedia.org/wiki/Alfred_Theodore_Goodwin', dutyStation:'Pasadena, CA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'J. Clifford Wallace', title:'Senior Judge', born:'1928',  court:'9th Cir.', nominatedBy:{name:'Nixon', party:'R', year:'1972'},url:'http://en.wikipedia.org/wiki/J._Clifford_Wallace', dutyStation:'San Diego, CA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'Procter Ralph Hug, Jr.', title:'Senior Judge', born:'1931',  court:'9th Cir.', nominatedBy:{name:'Carter', party:'D', year:'1977'},url:'http://en.wikipedia.org/wiki/Procter_Ralph_Hug_Jr.', dutyStation:'Reno, NV'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'Mary M. Schroeder', title:'Senior Judge', born:'1940',  court:'9th Cir.', nominatedBy:{name:'Carter', party:'D', year:'1979'},url:'http://en.wikipedia.org/wiki/Mary_M._Schroeder', dutyStation:'Phoenix, AZ'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'Joseph Jerome Farris', title:'Senior Judge', born:'1930',  court:'9th Cir.', nominatedBy:{name:'Carter', party:'D', year:'1979'},url:'http://en.wikipedia.org/wiki/Joseph_Jerome_Farris', dutyStation:'Seattle, WA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'Arthur Lawrence Alarcon', title:'Senior Judge', born:'1925',  court:'9th Cir.', nominatedBy:{name:'Carter', party:'D', year:'1979'},url:'http://en.wikipedia.org/wiki/Arthur_Lawrence_Alarcon', dutyStation:'Los Angeles, CA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'Dorothy Wright Nelson', title:'Senior Judge', born:'1928',  court:'9th Cir.', nominatedBy:{name:'Carter', party:'D', year:'1979'},url:'http://en.wikipedia.org/wiki/Dorothy_Wright_Nelson', dutyStation:'Pasadena, CA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'William Cameron Canby, Jr.', title:'Senior Judge', born:'1931',  court:'9th Cir.', nominatedBy:{name:'Carter', party:'D', year:'1980'},url:'http://en.wikipedia.org/wiki/William_Cameron_Canby,_Jr.', dutyStation:'Phoenix, AZ'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'John T. Noonan, Jr.', title:'Senior Judge', born:'1926',  court:'9th Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1985'},url:'http://en.wikipedia.org/wiki/John_T._Noonan,_Jr.', dutyStation:'San Francisco, CA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'Edward Leavy', title:'Senior Judge', born:'1929',  court:'9th Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1987'},url:'http://en.wikipedia.org/wiki/Edward_Leavy', dutyStation:'Portland, OR'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'Stephen S. Trott', title:'Senior Judge', born:'1939',  court:'9th Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1988'},url:'http://en.wikipedia.org/wiki/Stephen_S._Trott', dutyStation:'Boise, ID'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'Ferdinand Francis Fernandez', title:'Senior Judge', born:'1937',  court:'9th Cir.', nominatedBy:{name:'G.H.W. Bush', party:'R', year:'1989'},url:'http://en.wikipedia.org/wiki/Ferdinand_Francis_Fernandez', dutyStation:'Pasadena, CA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'Andrew Jay Kleinfeld', title:'Senior Judge', born:'1945',  court:'9th Cir.', nominatedBy:{name:'G.H.W. Bush', party:'R', year:'1991'},url:'http://en.wikipedia.org/wiki/Andrew_Jay_Kleinfeld', dutyStation:'Fairbanks, AK'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'Michael Daly Hawkins', title:'Senior Judge', born:'1945',  court:'9th Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1994'},url:'http://en.wikipedia.org/wiki/Michael_Daly_Hawkins', dutyStation:'Phoenix, AZ'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'A. Wallace Tashima', title:'Senior Judge', born:'1934',  court:'9th Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1996'},url:'http://en.wikipedia.org/wiki/A._Wallace_Tashima', dutyStation:'Pasadena, CA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Ninth_Circuit', name:'Raymond C. Fisher', title:'Senior Judge', born:'1939',  court:'9th Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1999'},url:'http://en.wikipedia.org/wiki/Raymond_C._Fisher', dutyStation:'Pasadena, CA'}





    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Tenth_Circuit', name:'Mary Beck Briscoe', title:'Chief Judge', born:'1947',  court:'10th Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1995'},url:'http://en.wikipedia.org/wiki/Mary_Beck_Briscoe', dutyStation:'Lawrence, KS'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Tenth_Circuit', name:'Paul Joseph Kelly, Jr.', title:'Circuit Judge', born:'1940',  court:'10th Cir.', nominatedBy:{name:'G.H.W. Bush', party:'R', year:'1992'},url:'http://en.wikipedia.org/wiki/Paul_Joseph_Kelly,_Jr.', dutyStation:'Santa Fe, NM'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Tenth_Circuit', name:'Carlos F. Lucero', title:'Circuit Judge', born:'1940',  court:'10th Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1995'},url:'http://en.wikipedia.org/wiki/Carlos_F._Lucero', dutyStation:'Denver, CO'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Tenth_Circuit', name:'Harris L Hartz', title:'Circuit Judge', born:'1947',  court:'10th Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2001'},url:'http://en.wikipedia.org/wiki/Harris_Hartz', dutyStation:'Albuquerque, NM'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Tenth_Circuit', name:'Timothy M. Tymkovich', title:'Circuit Judge', born:'1956',  court:'10th Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2003'},url:'http://en.wikipedia.org/wiki/Timothy_M._Tymkovich', dutyStation:'Denver, CO'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Tenth_Circuit', name:'Neil M. Gorsuch', title:'Circuit Judge', born:'1967',  court:'10th Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2006'},url:'http://en.wikipedia.org/wiki/Neil_M._Gorsuch', dutyStation:'Denver, CO'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Tenth_Circuit', name:'Jerome A. Holmes', title:'Circuit Judge', born:'1961',  court:'10th Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2006'},url:'http://en.wikipedia.org/wiki/Jerome_A._Holmes', dutyStation:'Oklahoma City, OK'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Tenth_Circuit', name:'Scott Matheson, Jr.', title:'Circuit Judge', born:'1953',  court:'10th Cir.', nominatedBy:{name:'Obama', party:'D', year:'2010'},url:'http://en.wikipedia.org/wiki/Scott_Matheson,_Jr.', dutyStation:'Salt Lake City, UT'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Tenth_Circuit', name:'Robert E. Bacharach', title:'Circuit Judge', born:'1959',  court:'10th Cir.', nominatedBy:{name:'Obama', party:'D', year:'2013'},url:'http://en.wikipedia.org/wiki/Robert_E._Bacharach', dutyStation:'Oklahoma City, OK'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Tenth_Circuit', name:'Gregory A. Phillips', title:'Circuit Judge', born:'1960',  court:'10th Cir.', nominatedBy:{name:'Obama', party:'D', year:'2013'},url:'http://en.wikipedia.org/wiki/Gregory_A._Phillips', dutyStation:'Cheyenne, WY'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Tenth_Circuit', name:'Carolyn B. McHugh', title:'Circuit Judge', born:'1957',  court:'10th Cir.', nominatedBy:{name:'Obama', party:'D', year:'2014'},url:'http://en.wikipedia.org/wiki/Carolyn_B._McHugh', dutyStation:'Salt Lake City, UT'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Tenth_Circuit', name:'Nancy Moritz', title:'Circuit Judge', born:'1960',  court:'10th Cir.', nominatedBy:{name:'Obama', party:'D', year:'beg.'},url:'http://en.wikipedia.org/wiki/Nancy_Moritz', dutyStation:'Lawrence, KS'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Tenth_Circuit', name:'Monroe G. McKay', title:'Senior Judge', born:'1928',  court:'10th Cir.', nominatedBy:{name:'Carter', party:'D', year:'1977'},url:'http://en.wikipedia.org/wiki/Monroe_G._McKay', dutyStation:'Salt Lake City, UT'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Tenth_Circuit', name:'Stephanie Kulp Seymour', title:'Senior Judge', born:'1940',  court:'10th Cir.', nominatedBy:{name:'Carter', party:'D', year:'1979'},url:'http://en.wikipedia.org/wiki/Stephanie_Kulp_Seymour', dutyStation:'Tulsa, OK'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Tenth_Circuit', name:'John Carbone Porfilio', title:'Senior Judge', born:'1934',  court:'10th Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1985'},url:'http://en.wikipedia.org/wiki/John_Carbone_Porfilio', dutyStation:'Loveland, CO'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Tenth_Circuit', name:'Stephen Hale Anderson', title:'Senior Judge', born:'1932',  court:'10th Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1985'},url:'http://en.wikipedia.org/wiki/Stephen_Hale_Anderson', dutyStation:'Salt Lake City, UT'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Tenth_Circuit', name:'Bobby Ray Baldock', title:'Senior Judge', born:'1936',  court:'10th Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1985'},url:'http://en.wikipedia.org/wiki/Bobby_Ray_Baldock', dutyStation:'Roswell, NM'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Tenth_Circuit', name:'Wade Brorby', title:'Senior Judge', born:'1934',  court:'10th Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1988'},url:'http://en.wikipedia.org/wiki/Wade_Brorby', dutyStation:'Cheyenne, WY'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Tenth_Circuit', name:'David M. Ebel', title:'Senior Judge', born:'1940',  court:'10th Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1988'},url:'http://en.wikipedia.org/wiki/David_M._Ebel', dutyStation:'Denver, CO'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Tenth_Circuit', name:'Michael R. Murphy', title:'Senior Judge', born:'1947',  court:'10th Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1995'},url:'http://en.wikipedia.org/wiki/Michael_R._Murphy', dutyStation:'Salt Lake City, UT'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Tenth_Circuit', name:'Terrence L. O\'Brien', title:'Senior Judge', born:'1943',  court:'10th Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2002'},url:'http://en.wikipedia.org/wiki/Terrence_L._O%27Brien', dutyStation:'Cheyenne, WY'}




    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Eleventh_Circuit', name:'Edward Earl Carnes', title:'Chief Judge', born:'1950',  court:'11th Cir.', nominatedBy:{name:'G.H.W. Bush', party:'R', year:'1992'},url:'http://en.wikipedia.org/wiki/Edward_Earl_Carnes', dutyStation:'Montgomery, AL'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Eleventh_Circuit', name:'Gerald Bard Tjoflat', title:'Circuit Judge', born:'1929',  court:'11th Cir.', nominatedBy:{name:'Ford[4]', party:'R', year:'1975'},url:'http://en.wikipedia.org/wiki/Gerald_Bard_Tjoflat', dutyStation:'Jacksonville, FL'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Eleventh_Circuit', name:'Frank M. Hull', title:'Circuit Judge', born:'1948',  court:'11th Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1997'},url:'http://en.wikipedia.org/wiki/Frank_M._Hull', dutyStation:'Atlanta, GA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Eleventh_Circuit', name:'Stanley Marcus', title:'Circuit Judge', born:'1946',  court:'11th Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1997'},url:'http://en.wikipedia.org/wiki/Stanley_Marcus_(judge)', dutyStation:'Miami, FL'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Eleventh_Circuit', name:'Charles R. Wilson', title:'Circuit Judge', born:'1954',  court:'11th Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1999'},url:'http://en.wikipedia.org/wiki/Charles_R._Wilson_(judge)', dutyStation:'Tampa, FL'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Eleventh_Circuit', name:'William H. Pryor, Jr.', title:'Circuit Judge', born:'1962',  court:'11th Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2005'},url:'http://en.wikipedia.org/wiki/William_H._Pryor,_Jr.', dutyStation:'Birmingham, AL'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Eleventh_Circuit', name:'Beverly B. Martin', title:'Circuit Judge', born:'1955',  court:'11th Cir.', nominatedBy:{name:'Obama', party:'D', year:'2010'},url:'http://en.wikipedia.org/wiki/Beverly_B._Martin', dutyStation:'Atlanta, GA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Eleventh_Circuit', name:'Adalberto Jordan', title:'Circuit Judge', born:'1961',  court:'11th Cir.', nominatedBy:{name:'Obama', party:'D', year:'2012'},url:'http://en.wikipedia.org/wiki/Adalberto_Jordan', dutyStation:'Miami, FL'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Eleventh_Circuit', name:'Robin S. Rosenbaum', title:'Circuit Judge', born:'1966',  court:'11th Cir.', nominatedBy:{name:'Obama', party:'D', year:'beg.'},url:'http://en.wikipedia.org/wiki/Robin_S._Rosenbaum', dutyStation:'—'}



    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Eleventh_Circuit', name:'James Clinkscales Hill', title:'Senior Judge', born:'1924',  court:'11th Cir.', nominatedBy:{name:'Ford[4]', party:'R', year:'1976'},url:'http://en.wikipedia.org/wiki/James_Clinkscales_Hill', dutyStation:'Jacksonville, FL'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Eleventh_Circuit', name:'Peter Thorp Fay', title:'Senior Judge', born:'1929',  court:'11th Cir.', nominatedBy:{name:'Ford[4]', party:'R', year:'1976'},url:'http://en.wikipedia.org/wiki/Peter_Thorp_Fay', dutyStation:'Miami, FL'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Eleventh_Circuit', name:'Phyllis A. Kravitch', title:'Senior Judge', born:'1920',  court:'11th Cir.', nominatedBy:{name:'Carter[4]', party:'D', year:'1979'},url:'http://en.wikipedia.org/wiki/Phyllis_A._Kravitch', dutyStation:'Atlanta, GA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Eleventh_Circuit', name:'R. Lanier Anderson III', title:'Senior Judge', born:'1936',  court:'11th Cir.', nominatedBy:{name:'Carter[4]', party:'D', year:'1979'},url:'http://en.wikipedia.org/wiki/R._Lanier_Anderson_III', dutyStation:'Macon, GA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Eleventh_Circuit', name:'James Larry Edmondson', title:'Senior Judge', born:'1947',  court:'11th Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1986'},url:'http://en.wikipedia.org/wiki/James_Larry_Edmondson', dutyStation:'Atlanta, GA'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Eleventh_Circuit', name:'Emmett Ripley Cox', title:'Senior Judge', born:'1935',  court:'11th Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1988'},url:'http://en.wikipedia.org/wiki/Emmett_Ripley_Cox', dutyStation:'Mobile, AL'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Eleventh_Circuit', name:'Joel Fredrick Dubina', title:'Senior Judge', born:'1947',  court:'11th Cir.', nominatedBy:{name:'G.H.W. Bush', party:'R', year:'1990'},url:'http://en.wikipedia.org/wiki/Joel_Fredrick_Dubina', dutyStation:'Montgomery, AL'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Eleventh_Circuit', name:'Susan Harrell Black', title:'Senior Judge', born:'1943',  court:'11th Cir.', nominatedBy:{name:'G.H.W. Bush', party:'R', year:'1992'},url:'http://en.wikipedia.org/wiki/Susan_Harrell_Black', dutyStation:'Jacksonville, FL'}




    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_District_of_Columbia_Circuit', name:'Merrick B. Garland', title:'Chief Judge', born:'1952',  court:'D.C. Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1997'},url:'http://en.wikipedia.org/wiki/Merrick_B._Garland', dutyStation:'Washington'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_District_of_Columbia_Circuit', name:'Karen L. Henderson', title:'Circuit Judge', born:'1944',  court:'D.C. Cir.', nominatedBy:{name:'G.H.W. Bush', party:'R', year:'1990'},url:'http://en.wikipedia.org/wiki/Karen_L._Henderson', dutyStation:'Washington'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_District_of_Columbia_Circuit', name:'Judith Ann Wilson Rogers', title:'Circuit Judge', born:'1939',  court:'D.C. Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1994'},url:'http://en.wikipedia.org/wiki/Judith_Ann_Wilson_Rogers', dutyStation:'Washington'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_District_of_Columbia_Circuit', name:'David S. Tatel', title:'Circuit Judge', born:'1942',  court:'D.C. Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1994'},url:'http://en.wikipedia.org/wiki/David_S._Tatel', dutyStation:'Washington'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_District_of_Columbia_Circuit', name:'Janice Rogers Brown', title:'Circuit Judge', born:'1949',  court:'D.C. Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2005'},url:'http://en.wikipedia.org/wiki/Janice_Rogers_Brown', dutyStation:'Washington'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_District_of_Columbia_Circuit', name:'Thomas B. Griffith', title:'Circuit Judge', born:'1954',  court:'D.C. Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2005'},url:'http://en.wikipedia.org/wiki/Thomas_B._Griffith', dutyStation:'Washington'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_District_of_Columbia_Circuit', name:'Brett M. Kavanaugh', title:'Circuit Judge', born:'1965',  court:'D.C. Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2006'},url:'http://en.wikipedia.org/wiki/Brett_M._Kavanaugh', dutyStation:'Washington'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_District_of_Columbia_Circuit', name:'Sri Srinivasan', title:'Circuit Judge', born:'1967',  court:'D.C. Cir.', nominatedBy:{name:'Obama', party:'D', year:'2013'},url:'http://en.wikipedia.org/wiki/Sri_Srinivasan', dutyStation:'Washington'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_District_of_Columbia_Circuit', name:'Patricia Ann Millett', title:'Circuit Judge', born:'1963',  court:'D.C. Cir.', nominatedBy:{name:'Obama', party:'D', year:'2013'},url:'http://en.wikipedia.org/wiki/Patricia_Ann_Millett', dutyStation:'Washington'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_District_of_Columbia_Circuit', name:'Nina Pillard', title:'Circuit Judge', born:'1961',  court:'D.C. Cir.', nominatedBy:{name:'Obama', party:'D', year:'2013'},url:'http://en.wikipedia.org/wiki/Nina_Pillard', dutyStation:'Washington'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_District_of_Columbia_Circuit', name:'Robert L. Wilkins', title:'Circuit Judge', born:'1963',  court:'D.C. Cir.', nominatedBy:{name:'Obama', party:'D', year:'2014'},url:'http://en.wikipedia.org/wiki/Robert_L._Wilkins', dutyStation:'Washington'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_District_of_Columbia_Circuit', name:'Harry T. Edwards', title:'Senior Judge', born:'1940',  court:'D.C. Cir.', nominatedBy:{name:'Carter', party:'D', year:'1980'},url:'http://en.wikipedia.org/wiki/Harry_T._Edwards', dutyStation:'Washington'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_District_of_Columbia_Circuit', name:'Laurence H. Silberman', title:'Senior Judge', born:'1935',  court:'D.C. Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1985'},url:'http://en.wikipedia.org/wiki/Laurence_H._Silberman', dutyStation:'Washington'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_District_of_Columbia_Circuit', name:'Stephen F. Williams', title:'Senior Judge', born:'1936',  court:'D.C. Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1986'},url:'http://en.wikipedia.org/wiki/Stephen_F._Williams', dutyStation:'Washington'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_District_of_Columbia_Circuit', name:'Douglas H. Ginsburg', title:'Senior Judge', born:'1946',  court:'D.C. Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1986'},url:'http://en.wikipedia.org/wiki/Douglas_H._Ginsburg', dutyStation:'Washington'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_District_of_Columbia_Circuit', name:'David B. Sentelle', title:'Senior Judge', born:'1943',  court:'D.C. Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1987'},url:'http://en.wikipedia.org/wiki/David_B._Sentelle', dutyStation:'Washington'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_District_of_Columbia_Circuit', name:'A. Raymond Randolph', title:'Senior Judge', born:'1943',  court:'D.C. Cir.', nominatedBy:{name:'G.H.W. Bush', party:'R', year:'1990'},url:'http://en.wikipedia.org/wiki/A._Raymond_Randolph', dutyStation:'Washington'}





    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Federal_Circuit', name:'Randall Ray Rader', title:'Chief Judge', born:'1949',  court:'Fed. Cir.', nominatedBy:{name:'G.H.W. Bush', party:'R', year:'1990'},url:'http://en.wikipedia.org/wiki/Randall_Ray_Rader', dutyStation:'Washington, DC'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Federal_Circuit', name:'Pauline Newman', title:'Circuit Judge', born:'1927',  court:'Fed. Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1984'},url:'http://en.wikipedia.org/wiki/Pauline_Newman', dutyStation:'Washington, DC'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Federal_Circuit', name:'Alan David Lourie', title:'Circuit Judge', born:'1935',  court:'Fed. Cir.', nominatedBy:{name:'G.H.W. Bush', party:'R', year:'1990'},url:'http://en.wikipedia.org/wiki/Alan_David_Lourie', dutyStation:'Washington, DC'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Federal_Circuit', name:'Timothy B. Dyk', title:'Circuit Judge', born:'1937',  court:'Fed. Cir.', nominatedBy:{name:'Clinton', party:'D', year:'2000'},url:'http://en.wikipedia.org/wiki/Timothy_B._Dyk', dutyStation:'Washington, DC'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Federal_Circuit', name:'Sharon Prost', title:'Circuit Judge', born:'1951',  court:'Fed. Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2001'},url:'http://en.wikipedia.org/wiki/Sharon_Prost', dutyStation:'Washington, DC'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Federal_Circuit', name:'Kimberly Ann Moore', title:'Circuit Judge', born:'1968',  court:'Fed. Cir.', nominatedBy:{name:'G.W. Bush', party:'R', year:'2006'},url:'http://en.wikipedia.org/wiki/Kimberly_Ann_Moore', dutyStation:'Washington, DC'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Federal_Circuit', name:'Kathleen M. O\'Malley', title:'Circuit Judge', born:'1956',  court:'Fed. Cir.', nominatedBy:{name:'Obama', party:'D', year:'2010'},url:'http://en.wikipedia.org/wiki/Kathleen_M._O%27Malley', dutyStation:'Washington, DC'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Federal_Circuit', name:'Jimmie V. Reyna', title:'Circuit Judge', born:'1952',  court:'Fed. Cir.', nominatedBy:{name:'Obama', party:'D', year:'2011'},url:'http://en.wikipedia.org/wiki/Jimmie_V._Reyna', dutyStation:'Washington, DC'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Federal_Circuit', name:'Evan Wallach', title:'Circuit Judge', born:'1949',  court:'Fed. Cir.', nominatedBy:{name:'Obama', party:'D', year:'2011'},url:'http://en.wikipedia.org/wiki/Evan_Wallach', dutyStation:'Washington, DC'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Federal_Circuit', name:'Richard G. Taranto', title:'Circuit Judge', born:'1957',  court:'Fed. Cir.', nominatedBy:{name:'Obama', party:'D', year:'2013'},url:'http://en.wikipedia.org/wiki/Richard_G._Taranto', dutyStation:'Washington, DC'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Federal_Circuit', name:'Raymond T. Chen', title:'Circuit Judge', born:'1968',  court:'Fed. Cir.', nominatedBy:{name:'Obama', party:'D', year:'2013'},url:'http://en.wikipedia.org/wiki/Raymond_T._Chen', dutyStation:'Washington, DC'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Federal_Circuit', name:'Todd M. Hughes', title:'Circuit Judge', born:'1966',  court:'Fed. Cir.', nominatedBy:{name:'Obama', party:'D', year:'2013'},url:'http://en.wikipedia.org/wiki/Todd_M._Hughes', dutyStation:'Washington, DC'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Federal_Circuit', name:'Haldane Robert Mayer', title:'Senior Judge', born:'1941',  court:'Fed. Cir.', nominatedBy:{name:'Reagan', party:'R', year:'1987'},url:'http://en.wikipedia.org/wiki/Haldane_Robert_Mayer', dutyStation:'Washington, DC'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Federal_Circuit', name:'S. Jay Plager', title:'Senior Judge', born:'1931',  court:'Fed. Cir.', nominatedBy:{name:'G.H.W. Bush', party:'R', year:'1989'},url:'http://en.wikipedia.org/wiki/S._Jay_Plager', dutyStation:'Washington, DC'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Federal_Circuit', name:'Raymond Charles Clevenger III', title:'Senior Judge', born:'1937',  court:'Fed. Cir.', nominatedBy:{name:'G.H.W. Bush', party:'R', year:'1990'},url:'http://en.wikipedia.org/wiki/Raymond_Charles_Clevenger_III', dutyStation:'Washington, DC'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Federal_Circuit', name:'Alvin Anthony Schall', title:'Senior Judge', born:'1944',  court:'Fed. Cir.', nominatedBy:{name:'G.H.W. Bush', party:'R', year:'1992'},url:'http://en.wikipedia.org/wiki/Alvin_Anthony_Schall', dutyStation:'Washington, DC'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Federal_Circuit', name:'William Curtis Bryson', title:'Senior Judge', born:'1945',  court:'Fed. Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1994'},url:'http://en.wikipedia.org/wiki/William_Curtis_Bryson', dutyStation:'Washington, DC'}
    ,{originalDataSource:'http://en.wikipedia.org/wiki/United_States_Court_of_Appeals_for_the_Federal_Circuit', name:'Richard Linn', title:'Senior Judge', born:'1944',  court:'Fed. Cir.', nominatedBy:{name:'Clinton', party:'D', year:'1999'},url:'http://en.wikipedia.org/wiki/Richard_Linn', dutyStation:'Washington, DC'}


];

var judgesGroupedByCitation = {};

judges.forEach(function(j) {

    if (isUndefined(judgesGroupedByCitation[j.court])) {
        judgesGroupedByCitation[j.court] = {inactive:[], active:[], senior:[], nonSenior:[]};


        judgesGroupedByCitation[j.court].activeByParty = {};

        judgesGroupedByCitation[j.court].activeByParty["r"] = [];
        judgesGroupedByCitation[j.court].activeByParty["d"] = [];

    }

    var theseJudges = judgesGroupedByCitation[j.court];

    if (j.dutyStation && j.dutyStation.indexOf("inactive")>-1) {
        theseJudges.inactive.push(j);
    }
    else {
        theseJudges.active.push(j);

        judgesGroupedByCitation[j.court].activeByParty[j.nominatedBy.party.toLowerCase()].push(j);

        if (j.title.toLowerCase().indexOf("senior")>-1) {
            theseJudges.senior.push(j);
        }
        else {
            theseJudges.nonSenior.push(j);

            if (j.title.toLowerCase().indexOf("chief")>-1) {
                theseJudges.chiefJustice = j;
            }

        }
    }


});
