/**
 * Created by bradflyon on 5/23/14.
 */

//there are some special ones that indicate that you need to look at the state
//



var scdbCourts = [
{id:1, name:'U.S. Court of Customs and Patent Appeals'},
{id:2, name:'U.S. Court of International Trade'},
{id:3, name:'U.S. Court of Claims, Court of Federal Claims'},
{id:4, name:'U.S. Court of Military Appeals, renamed as Court of Appeals for the Armed Forces'},
{id:5, name:'U.S. Court of Military Review'},
{id:6, name:'U.S. Court of Veterans Appeals'},
{id:7, name:'U.S. Customs Court'},
{id:8, name:'U.S. Court of Appeals, Federal Circuit'},
{id:9, name:'U.S. Tax Court'},
{id:10, name:'Temporary Emergency U.S. Court of Appeals'},
{id:12, name:'U.S. Court for China'},
{id:13, name:'U.S. Consular Courts'},
{id:14, name:'U.S. Commerce Court'},
{id:15, name:'Territorial Supreme Court'},
{id:16, name:'Territorial Appellate Court'},
{id:17, name:'Territorial Trial Court'},
{id:18, name:'Emergency Court of Appeals'},
{id:19, name:'District of Columbia Supreme Court'},
{id:20, name:'Bankruptcy Court'},
{id:21, name:'U.S. Court of Appeals, First Circuit'},
{id:22, name:'U.S. Court of Appeals, Second Circuit'},
{id:23, name:'U.S. Court of Appeals, Third Circuit'},
{id:24, name:'U.S. Court of Appeals, Fourth Circuit'},
{id:25, name:'U.S. Court of Appeals, Fifth Circuit'},
{id:26, name:'U.S. Court of Appeals, Sixth Circuit'},
{id:27, name:'U.S. Court of Appeals, Seventh Circuit'},
{id:28, name:'U.S. Court of Appeals, Eighth Circuit'},
{id:29, name:'U.S. Court of Appeals, Ninth Circuit'},
{id:30, name:'U.S. Court of Appeals, Tenth Circuit'},
{id:31, name:'U.S. Court of Appeals, Eleventh Circuit'},
{id:32, name:'U.S. Court of Appeals, District of Columbia Circuit'},
{id:41, name:'Alabama Middle U.S. District Court'},
{id:42, name:'Alabama Northern U.S. District Court'},
{id:43, name:'Alabama Southern U.S. District Court'},
{id:44, name:'Alaska U.S. District Court'},
{id:45, name:'Arizona U.S. District Court'},
{id:46, name:'Arkansas Eastern U.S. District Court'},
{id:47, name:'Arkansas Western U.S. District Court'},
{id:48, name:'California Central U.S. District Court'},
{id:49, name:'California Eastern U.S. District Court'},
{id:50, name:'California Northern U.S. District Court'},
{id:51, name:'California Southern U.S. District Court'},
{id:52, name:'Colorado U.S. District Court'},
{id:53, name:'Connecticut U.S. District Court'},
{id:54, name:'Delaware U.S. District Court'},
{id:55, name:'District Of Columbia U.S. District Court'},
{id:56, name:'Florida Middle U.S. District Court'},
{id:57, name:'Florida Northern U.S. District Court'},
{id:58, name:'Florida Southern U.S. District Court'},
{id:59, name:'Georgia Middle U.S. District Court'},
{id:60, name:'Georgia Northern U.S. District Court'},
{id:61, name:'Georgia Southern U.S. District Court'},
{id:62, name:'Guam U.S. District Court'},
{id:63, name:'Hawaii U.S. District Court'},
{id:64, name:'Idaho U.S. District Court'},
{id:65, name:'Illinois Central U.S. District Court'},
{id:66, name:'Illinois Northern U.S. District Court'},
{id:67, name:'Illinois Southern U.S. District Court'},
{id:68, name:'Indiana Northern U.S. District Court'},
{id:69, name:'Indiana Southern U.S. District Court'},
{id:70, name:'Iowa Northern U.S. District Court'},
{id:71, name:'Iowa Southern U.S. District Court'},
{id:72, name:'Kansas U.S. District Court'},
{id:73, name:'Kentucky Eastern U.S. District Court'},
{id:74, name:'Kentucky Western U.S. District Court'},
{id:75, name:'Louisiana Eastern U.S. District Court'},
{id:76, name:'Louisiana Middle U.S. District Court'},
{id:77, name:'Louisiana Western U.S. District Court'},
{id:78, name:'Maine U.S. District Court'},
{id:79, name:'Maryland U.S. District Court'},
{id:80, name:'Massachusetts U.S. District Court'},
{id:81, name:'Michigan Eastern U.S. District Court'},
{id:82, name:'Michigan Western U.S. District Court'},
{id:83, name:'Minnesota U.S. District Court'},
{id:84, name:'Mississippi Northern U.S. District Court'},
{id:85, name:'Mississippi Southern U.S. District Court'},
{id:86, name:'Missouri Eastern U.S. District Court'},
{id:87, name:'Missouri Western U.S. District Court'},
{id:88, name:'Montana U.S. District Court'},
{id:89, name:'Nebraska U.S. District Court'},
{id:90, name:'Nevada U.S. District Court'},
{id:91, name:'New Hampshire U.S. District Court'},
{id:92, name:'New Jersey U.S. District Court'},
{id:93, name:'New Mexico U.S. District Court'},
{id:94, name:'New York Eastern U.S. District Court'},
{id:95, name:'New York Northern U.S. District Court'},
{id:96, name:'New York Southern U.S. District Court'},
{id:97, name:'New York Western U.S. District Court'},
{id:98, name:'North Carolina Eastern U.S. District Court'},
{id:99, name:'North Carolina Middle U.S. District Court'},
{id:100, name:'North Carolina Western U.S. District Court'},
{id:101, name:'North Dakota U.S. District Court'},
{id:102, name:'Northern Mariana Islands U.S. District Court'},
{id:103, name:'Ohio Northern U.S. District Court'},
{id:104, name:'Ohio Southern U.S. District Court'},
{id:105, name:'Oklahoma Eastern U.S. District Court'},
{id:106, name:'Oklahoma Northern U.S. District Court'},
{id:107, name:'Oklahoma Western U.S. District Court'},
{id:108, name:'Oregon U.S. District Court'},
{id:109, name:'Pennsylvania Eastern U.S. District Court'},
{id:110, name:'Pennsylvania Middle U.S. District Court'},
{id:111, name:'Pennsylvania Western U.S. District Court'},
{id:112, name:'Puerto Rico U.S. District Court'},
{id:113, name:'Rhode Island U.S. District Court'},
{id:114, name:'South Carolina U.S. District Court'},
{id:115, name:'South Dakota U.S. District Court'},
{id:116, name:'Tennessee Eastern U.S. District Court'},
{id:117, name:'Tennessee Middle U.S. District Court'},
{id:118, name:'Tennessee Western U.S. District Court'},
{id:119, name:'Texas Eastern U.S. District Court'},
{id:120, name:'Texas Northern U.S. District Court'},
{id:121, name:'Texas Southern U.S. District Court'},
{id:122, name:'Texas Western U.S. District Court'},
{id:123, name:'Utah U.S. District Court'},
{id:124, name:'Vermont U.S. District Court'},
{id:125, name:'Virgin Islands U.S. District Court'},
{id:126, name:'Virginia Eastern U.S. District Court'},
{id:127, name:'Virginia Western U.S. District Court'},
{id:128, name:'Washington Eastern U.S. District Court'},
{id:129, name:'Washington Western U.S. District Court'},
{id:130, name:'West Virginia Northern U.S. District Court'},
{id:131, name:'West Virginia Southern U.S. District Court'},
{id:132, name:'Wisconsin Eastern U.S. District Court'},
{id:133, name:'Wisconsin Western U.S. District Court'},
{id:134, name:'Wyoming U.S. District Court'},
{id:150, name:'Louisiana U.S. District Court'},
{id:151, name:'Washington U.S. District Court'},
{id:152, name:'West Virginia U.S. District Court'},
{id:153, name:'Illinois Eastern U.S. District Court'},
{id:155, name:'South Carolina Eastern U.S. District Court'},
{id:160, name:'South Carolina Western U.S. District Court'},
{id:162, name:'Alabama U.S. District Court'},
{id:163, name:'U.S. District Court for the Canal Zone'},
{id:164, name:'Georgia U.S. District Court'},
{id:165, name:'Illinois U.S. District Court'},
{id:166, name:'Indiana U.S. District Court'},
{id:167, name:'Iowa U.S. District Court'},
{id:168, name:'Michigan U.S. District Court'},
{id:169, name:'Mississippi U.S. District Court'},
{id:170, name:'Missouri U.S. District Court'},
{id:171, name:'New Jersey Eastern U.S. District Court (East Jersey U.S. District Court)'},
{id:172, name:'New Jersey Western U.S. District Court (West Jersey U.S. District Court)'},
{id:173, name:'New York U.S. District Court'},
{id:174, name:'North Carolina U.S. District Court'},
{id:175, name:'Ohio U.S. District Court'},
{id:176, name:'Pennsylvania U.S. District Court'},
{id:177, name:'Tennessee U.S. District Court'},
{id:178, name:'Texas U.S. District Court'},
{id:179, name:'Virginia U.S. District Court'},
{id:180, name:'Norfolk U.S. District Court'},
{id:181, name:'Wisconsin U.S. District Court'},
{id:182, name:'Kentucky U.S. Distrcrict Court'},
{id:183, name:'New Jersey U.S. District Court'},
{id:184, name:'California U.S. District Court'},
{id:185, name:'Florida U.S. District Court'},
{id:186, name:'Arkansas U.S. District Court'},
{id:187, name:'District of Orleans U.S. District Court'},
{id:300, name:'State Supreme Court'},
{id:301, name:'State Appellate Court'},
{id:302, name:'State Trial Court'},
{id:400, name:'Eastern Circuit (of the United States)'},
{id:401, name:'Middle Circuit (of the United States)'},
{id:402, name:'Southern Circuit (of the United States)'},
{id:403, name:'Alabama U.S. Circuit Court for (all) District(s) of Alabama'},
{id:404, name:'Arkansas U.S. Circuit Court for (all) District(s) of Arkansas'},
{id:405, name:'California U.S. Circuit for (all) District(s) of California'},
{id:406, name:'Connecticut U.S. Circuit for the District of Connecticut'},
{id:407, name:'Delaware U.S. Circuit for the District of Delaware'},
{id:408, name:'Florida U.S. Circuit for (all) District(s) of Florida'},
{id:409, name:'Georgia U.S. Circuit for (all) District(s) of Georgia'},
{id:410, name:'Illinois U.S. Circuit for (all) District(s) of Illinois'},
{id:411, name:'Indiana U.S. Circuit for (all) District(s) of Indiana'},
{id:412, name:'Iowa U.S. Circuit for (all) District(s) of Iowa'},
{id:413, name:'Kansas U.S. Circuit for the District of Kansas'},
{id:414, name:'Kentucky U.S. Circuit for (all) District(s) of Kentucky'},
{id:415, name:'Louisiana U.S. Circuit for (all) District(s) of Louisiana'},
{id:416, name:'Maine U.S. Circuit for the District of Maine'},
{id:417, name:'Maryland U.S. Circuit for the District of Maryland'},
{id:418, name:'Massachusetts U.S. Circuit for the District of Massachusetts'},
{id:419, name:'Michigan U.S. Circuit for (all) District(s) of Michigan'},
{id:420, name:'Minnesota U.S. Circuit for the District of Minnesota'},
{id:421, name:'Mississippi U.S. Circuit for (all) District(s) of Mississippi'},
{id:422, name:'Missouri U.S. Circuit for (all) District(s) of Missouri'},
{id:423, name:'Nevada U.S. Circuit for the District of Nevada'},
{id:424, name:'New Hampshire U.S. Circuit for the District of New Hampshire'},
{id:425, name:'New Jersey U.S. Circuit for (all) District(s) of New Jersey'},
{id:426, name:'New York U.S. Circuit for (all) District(s) of New York'},
{id:427, name:'North Carolina U.S. Circuit for (all) District(s) of North Carolina'},
{id:428, name:'Ohio U.S. Circuit for (all) District(s) of Ohio'},
{id:429, name:'Oregon U.S. Circuit for the District of Oregon'},
{id:430, name:'Pennsylvania U.S. Circuit for (all) District(s) of Pennsylvania'},
{id:431, name:'Rhode Island U.S. Circuit for the District of Rhode Island'},
{id:432, name:'South Carolina U.S. Circuit for the District of South Carolina'},
{id:433, name:'Tennessee U.S. Circuit for (all) District(s) of Tennessee'},
{id:434, name:'Texas U.S. Circuit for (all) District(s) of Texas'},
{id:435, name:'Vermont U.S. Circuit for the District of Vermont'},
{id:436, name:'Virginia U.S. Circuit for (all) District(s) of Virginia'},
{id:437, name:'West Virginia U.S. Circuit for (all) District(s) of West Virginia'},
{id:438, name:'Wisconsin U.S. Circuit for (all) District(s) of Wisconsin'},
{id:439, name:'Wyoming U.S. Circuit for the District of Wyoming'},
{id:440, name:'Circuit Court of the District of Columbia'},
{id:441, name:'Nebraska U.S. Circuit for the District of Nebraska'},
{id:442, name:'Colorado U.S. Circuit for the District of Colorado'},
{id:443, name:'Washington U.S. Circuit for (all) District(s) of Washington'}
];


var scdbCourtsById = {};
scdbCourts.forEach(function(c) {
    scdbCourts[c.id] = c;
});

var scdbStates = [
    {id:1, state:'Alabama'},
    {id:2, state:'Alaska'},
    {id:3, state:'American Samoa'},
    {id:4, state:'Arizona'},
    {id:5, state:'Arkansas'},
    {id:6, state:'California'},
    {id:7, state:'Colorado'},
    {id:8, state:'Connecticut'},
    {id:9, state:'Delaware'},
    {id:10, state:'District of Columbia'},
    {id:11, state:'Federated States of Micronesia'},
    {id:12, state:'Florida'},
    {id:13, state:'Georgia'},
    {id:14, state:'Guam'},
    {id:15, state:'Hawaii'},
    {id:16, state:'Idaho'},
    {id:17, state:'Illinois'},
    {id:18, state:'Indiana'},
    {id:19, state:'Iowa'},
    {id:20, state:'Kansas'},
    {id:21, state:'Kentucky'},
    {id:22, state:'Louisiana'},
    {id:23, state:'Maine'},
    {id:24, state:'Marshall Islands'},
    {id:25, state:'Maryland'},
    {id:26, state:'Massachusetts'},
    {id:27, state:'Michigan'},
    {id:28, state:'Minnesota'},
    {id:29, state:'Mississippi'},
    {id:30, state:'Missouri'},
    {id:31, state:'Montana'},
    {id:32, state:'Nebraska'},
    {id:33, state:'Nevada'},
    {id:34, state:'New Hampshire'},
    {id:35, state:'New Jersey'},
    {id:36, state:'New Mexico'},
    {id:37, state:'New York'},
    {id:38, state:'North Carolina'},
    {id:39, state:'North Dakota'},
    {id:40, state:'Northern Mariana Islands'},
    {id:41, state:'Ohio'},
    {id:42, state:'Oklahoma'},
    {id:43, state:'Oregon'},
    {id:44, state:'Palau'},
    {id:45, state:'Pennsylvania'},
    {id:46, state:'Puerto Rico'},
    {id:47, state:'Rhode Island'},
    {id:48, state:'South Carolina'},
    {id:49, state:'South Dakota'},
    {id:50, state:'Tennessee'},
    {id:51, state:'Texas'},
    {id:52, state:'Utah'},
    {id:53, state:'Vermont'},
    {id:54, state:'Virgin Islands'},
    {id:55, state:'Virginia'},
    {id:56, state:'Washington'},
    {id:57, state:'West Virginia'},
    {id:58, state:'Wisconsin'},
    {id:59, state:'Wyoming'},
    {id:60, state:'United States'},
    {id:61, state:'Interstate Compact'},
    {id:62, state:'Philippines'}
];


var scdbStatesById = {};
scdbStates.forEach(function(state) {
    scdbStatesById[state.id] = state;
});

//variable name: jurisdiction
var mannerSupremeCourtTakesCase =
[
{id: 1, value:'cert'},
{id: 2, value:'appeal'},
{id: 3, value:'bail'},
{id: 4, value:'certification'},
{id: 5, value:'docketing fee'},
{id: 6, value:'rehearing or restored to calendar for reargument'},
{id: 7, value:'injunction'},
{id: 8, value:'mandamus'},
{id: 9, value:'original'},
    {id: 10, value:'NA'},
    {id: 11, value:'NA'},
{id: 12, value:'stay'},
{id: 13, value:'writ of error'},
{id: 14, value:'writ of habeas corpus'},
{id: 15, value:'unspecified, other'}
];

var mannerSupremeCourtTakesCaseById = {};
mannerSupremeCourtTakesCase.forEach(function(c) {
    mannerSupremeCourtTakesCaseById[c.id] = c;
});


var certReason = [
    {id:1, name:'case did not arise on cert or cert not granted'},
    {id:2, name:'federal court conﬂict'},
    {id:3, name:'federal court conﬂict and to resolve important or signiﬁcant question'},
    {id:4, name:'putative conﬂict'},
    {id:5, name:'conﬂict between federal court and state court'},
    {id:6, name:'state court conﬂict'},
    {id:7, name:'federal court confusion or uncertainty'},
    {id:8, name:'state court confusion or uncertainty'},
    {id:9, name:'federal court and state court confusion or uncertainty'},
    {id:10, name:'to resolve important or signiﬁcant question'},
    {id:11, name:'to resolve question presented'},
    {id:12, name:'no reason given'},
    {id:13, name:'other reason'}
];

var certReasonById = {};
certReason.forEach(function(c) {
    certReasonById[c.id] = c;
});

var issueById = {};
var issue = [
    {id:10010, name:'involuntary confession'},
    {id:10020, name:'habeas corpus'},
    {id:10030, name:'plea bargaining: the constitutionality of and/or the circumstances of its exercise'},
    {id:10040, name:'retroactivity (of newly announced or newly enacted constitutional or statutory rights)'},
    {id:10050, name:'search and seizure (other than as pertains to vehicles or Crime Control Act)'},
    {id:10060, name:'search and seizure, vehicles'},
    {id:10070, name:'search and seizure, Crime Control Act'},
    {id:10080, name:'contempt of court or congress'},
    {id:10090, name:'self-incrimination (other than as pertains to Miranda or immunity from prosecution)'},
    {id:10100, name:'Miranda warnings'},
    {id:10110, name:'self-incrimination, immunity from prosecution'},
    {id:10120, name:'right to counsel (cf. indigents appointment of counsel or inadequate representation)'},
    {id:10130, name:'cruel and unusual punishment, death penalty (cf. extra legal jury influence, death penalty)'},
    {id:10140, name:'cruel and unusual punishment, non-death penalty (cf. liability, civil rights acts)'},
    {id:10150, name:'line-up Note: admissibility into evidence of identification obtained after accused was taken into custody, or after indictment or information'},
    {id:10160, name:'discovery and inspection (in the context of criminal litigation only, otherwise Freedom of Information Act and related federal or state statutes or regulations)'},
    {id:10170, name:'double jeopardy'},
    {id:10180, name:'ex post facto (state)'},
    {id:10190, name:'extra-legal jury influences: miscellaneous Note: no question regarding the right to a jury trial or to a speedy trial (these belong in jury trial and speedy trial, respectively); the focus, rather, is on the fairness to the accused when jurors are exposed to the influences specified'},
    {id:10200, name:'extra-legal jury influences: prejudicial statements or evidence'},
    {id:10210, name:'extra-legal jury influences: contact with jurors outside courtroom'},
    {id:10220, name:'extra-legal jury influences: jury instructions (not necessarily in criminal cases)'},
    {id:10230, name:'extra-legal jury influences: voir dire (not necessarily a criminal case)'},
    {id:10240, name:'extra-legal jury influences: prison garb or appearance'},
    {id:10250, name:'extra-legal jury influences: jurors and death penalty (cf. cruel and unusual punishment)'},
    {id:10260, name:'extra-legal jury influences: pretrial publicity'},
    {id:10270, name:'confrontation (right to confront accuser, call and cross-examine witnesses)'},
    {id:10280, name:'subconstitutional fair procedure: confession of error Note: nonsubstantive rules and procedures pertaining to the administration of justice that do not rise to the level of a constitutional matter. This is the residual category insofar as criminal procedure is concerned. Note that this issue need not necessarily pertain to a criminal action. If the case involves an indigent, consider indigent categories.'},
    {id:10290, name:'subconstitutional fair procedure: conspiracy (cf. Federal Rules of Criminal Procedure: conspiracy) Note: nonsubstantive rules and procedures pertaining to the administration of justice that do not rise to the level of a constitutional matter. This is the residual category insofar as criminal procedure is concerned. Note that this issue need not necessarily pertain to a criminal action. If the case involves an indigent, consider indigent categories.'},
    {id:10300, name:'subconstitutional fair procedure: entrapment Note: nonsubstantive rules and procedures pertaining to the administration of justice that do not rise to the level of a constitutional matter. This is the residual category insofar as criminal procedure is concerned. Note that this issue need not necessarily pertain to a criminal action. If the case involves an indigent, consider indigent categories.'},
    {id:10310, name:'subconstitutional fair procedure: exhaustion of remedies Note: nonsubstantive rules and procedures pertaining to the administration of justice that do not rise to the level of a constitutional matter. This is the residual category insofar as criminal procedure is concerned. Note that this issue need not necessarily pertain to a criminal action. If the case involves an indigent, consider indigent categories.'},
    {id:10320, name:'subconstitutional fair procedure: fugitive from justice Note: nonsubstantive rules and procedures pertaining to the administration of justice that do not rise to the level of a constitutional matter. This is the residual category insofar as criminal procedure is concerned. Note that this issue need not necessarily pertain to a criminal action. If the case involves an indigent, consider indigent categories.'},
    {id:10330, name:'subconstitutional fair procedure: presentation, admissibility, or sufficiency of evidence (not necessarily a criminal case) Note: nonsubstantive rules and procedures pertaining to the administration of justice that do not rise to the level of a constitutional matter. This is the residual category insofar as criminal procedure is concerned. Note that this issue need not necessarily pertain to a criminal action. If the case involves an indigent, consider indigent categories.'},
    {id:10340, name:'subconstitutional fair procedure: stay of execution Note: nonsubstantive rules and procedures pertaining to the administration of justice that do not rise to the level of a constitutional matter. This is the residual category insofar as criminal procedure is concerned. Note that this issue need not necessarily pertain to a criminal action. If the case involves an indigent, consider indigent categories.'},
    {id:10350, name:'subconstitutional fair procedure: timeliness Note: nonsubstantive rules and procedures pertaining to the administration of justice that do not rise to the level of a constitutional matter. This is the residual category insofar as criminal procedure is concerned. Note that this issue need not necessarily pertain to a criminal action. If the case involves an indigent, consider indigent categories.'},
    {id:10360, name:'subconstitutional fair procedure: miscellaneous Note: nonsubstantive rules and procedures pertaining to the administration of justice that do not rise to the level of a constitutional matter. This is the residual category insofar as criminal procedure is concerned. Note that this issue need not necessarily pertain to a criminal action. If the case involves an indigent, consider indigent categories.'},
    {id:10370, name:'Federal Rules of Criminal Procedure Note: including application of the Federal Rules of Evidence in criminal proceedings and criminal rules of a court of appeals or state supreme court'},
    {id:10380, name:'statutory construction of criminal laws: assault Note: these codes, by definition exclude the constitutionality of these laws'},
    {id:10390, name:'statutory construction of criminal laws: bank robbery Note: these codes, by definition exclude the constitutionality of these laws'},
    {id:10400, name:'statutory construction of criminal laws: conspiracy (cf. subconstitutional fair procedure: conspiracy) Note: these codes, by definition exclude the constitutionality of these laws'},
    {id:10410, name:'statutory construction of criminal laws: escape from custody Note: these codes, by definition exclude the constitutionality of these laws'},
    {id:10420, name:'statutory construction of criminal laws: false statements (cf. statutory construction of criminal laws: perjury) Note: these codes, by definition exclude the constitutionality of these laws'},
    {id:10430, name:'statutory construction of criminal laws: financial (other than in fraud or internal revenue) Note: these codes, by definition exclude the constitutionality of these laws'},
    {id:10440, name:'statutory construction of criminal laws: firearms Note: these codes, by definition exclude the constitutionality of these laws'},
    {id:10450, name:'statutory construction of criminal laws: fraud Note: these codes, by definition exclude the constitutionality of these laws'},
    {id:10460, name:'statutory construction of criminal laws: gambling Note: these codes, by definition exclude the constitutionality of these laws'},
    {id:10470, name:'statutory construction of criminal laws: Hobbs Act; i.e., 18 USC 1951 Note: these codes, by definition exclude the constitutionality of these laws; not 28 USC 2341, the Administrative Orders Review Act'},
    {id:10480, name:'statutory construction of criminal laws: immigration (cf. immigration and naturalization) Note: these codes, by definition exclude the constitutionality of these laws'},
    {id:10490, name:'statutory construction of criminal laws: internal revenue (cf. Federal Taxation) Note: these codes, by definition exclude the constitutionality of these laws'},
    {id:10500, name:'statutory construction of criminal laws: Mann Act and related statutes Note: these codes, by definition exclude the constitutionality of these laws'},
    {id:10510, name:'statutory construction of criminal laws: narcotics includes regulation and prohibition of alcohol Note: these codes, by definition exclude the constitutionality of these laws'},
    {id:10520, name:'statutory construction of criminal laws: obstruction of justice Note: these codes, by definition exclude the constitutionality of these laws'},
    {id:10530, name:'statutory construction of criminal laws: perjury (other than as pertains to statutory construction of criminal laws: false statements) Note: these codes, by definition exclude the constitutionality of these laws'},
    {id:10540, name:'statutory construction of criminal laws: Travel Act, 18 USC 1952 Note: these codes, by definition exclude the constitutionality of these laws'},
    {id:10550, name:'statutory construction of criminal laws: war crimes Note: these codes, by definition exclude the constitutionality of these laws'},
    {id:10560, name:'statutory construction of criminal laws: sentencing guidelines Note: these codes, by definition exclude the constitutionality of these laws'},
    {id:10570, name:'statutory construction of criminal laws: miscellaneous Note: these codes, by definition exclude the constitutionality of these laws'},
    {id:10580, name:'jury trial (right to, as distinct from extra-legal jury influences)'},
    {id:10590, name:'speedy trial'},
    {id:10595, name:'incorporation of foreign territories'},
    {id:10600, name:'miscellaneous criminal procedure (cf. due process, prisoners\' rights, comity: criminal procedure)'},
{id:20010, name:'voting'},
{id:20020, name:'Voting Rights Act of 1965, plus amendments'},
{id:20030, name:'ballot access (of candidates and political parties)'},
{id:20040, name:'desegregation (other than as pertains to school desegregation, employment discrimination, and affirmative action)'},
{id:20050, name:'desegregation, schools'},
{id:20060, name:'employment discrimination: on basis of race, age, religion, illegitimacy, national origin, or working conditions. Note: Not alienage, which is employability of aliens, or gender, which is sex discrimination in employment.'},
{id:20070, name:'affirmative action'},
{id:20075, name:'slavery or indenture'},
{id:20080, name:'sit-in demonstrations (protests against racial discrimination in places of public accommodation) Note: To be sharply distinguished from protests not involving racial discrimination. The latter are coded as protest demonstrations.'},
{id:20090, name:'reapportionment: other than plans governed by the Voting Rights Act'},
{id:20100, name:'debtors\' rights'},
    {id:20110, name:'deportation (cf. immigration and naturalization)'},
    {id:20120, name:'employability of aliens (cf. immigration and naturalization)'},
    {id:20130, name:'sex discrimination (excluding sex discrimination in employment)'},
    {id:20140, name:'sex discrimination in employment (cf. sex discrimination and employment discrimination)'},
    {id:20150, name:'Indians (other than pertains to state jurisdiction over)'},
    {id:20160, name:'Indians, state jurisdiction over'},
    {id:20170, name:'juveniles (cf. rights of illegitimates)'},
    {id:20180, name:'poverty law, constitutional Note: typically equal protection challenges over welfare benefits, including pension and medical benefits'},
    {id:20190, name:'poverty law, statutory: welfare benefits, typically under some Social Security Act provision. Note: Excludes rights of illegitimates and rights of handicapped'},
    {id:20200, name:'illegitimates, rights of (cf. juveniles): typically inheritance and survivor\'s benefits, and paternity suits'},
        {id:20210, name:'handicapped, rights of: under Rehabilitation, Americans with Disabilities Act, and related statutes'},
        {id:20220, name:'residency requirements: durational, plus discrimination against nonresidents'},
        {id:20230, name:'military: draftee, or person subject to induction Note: cf. conscientious objectors and comity: military'},
        {id:20240, name:'military: active duty Note: cf. conscientious objectors and comity: military'},
        {id:20250, name:'military: veteran Note: cf. conscientious objectors and comity: military'},
        {id:20260, name:'immigration and naturalization: permanent residence Note: cf. statutory construction of criminal laws: immigration, deportation, and employability of aliens'},
        {id:20270, name:'immigration and naturalization: citizenship Note: cf. statutory construction of criminal laws: immigration, deportation, and employability of aliens'},
        {id:20280, name:'immigration and naturalization: loss of citizenship, denaturalization Note: cf. statutory construction of criminal laws: immigration, deportation, and employability of aliens'},
        {id:20290, name:'immigration and naturalization: access to public education Note: cf. statutory construction of criminal laws: immigration, deportation, and employability of aliens'},
        {id:20300, name:'immigration and naturalization: welfare benefits Note: cf. statutory construction of criminal laws: immigration, deportation, and employability of aliens'},
        {id:20310, name:'immigration and naturalization: miscellaneous Note: cf. statutory construction of criminal laws: immigration, deportation, and employability of aliens'},
        {id:20320, name:'indigents: appointment of counsel (cf. right to counsel) Note: procedural protections for indigents because of their indigency. Typically in matters pertaining to criminal justice. cf. poverty law, constitutional and poverty law, statutory.'},
        {id:20330, name:'indigents: inadequate representation by counsel (cf. right to counsel) Note: procedural protections for indigents because of their indigency. Typically in matters pertaining to criminal justice. cf. poverty law, constitutional and poverty law, statutory.'},
        {id:20340, name:'indigents: payment of fine Note: procedural protections for indigents because of their indigency. Typically in matters pertaining to criminal justice. cf. poverty law, constitutional and poverty law, statutory.'},
        {id:20350, name:'indigents: costs or filing fees Note: procedural protections for indigents because of their indigency. Typically in matters pertaining to criminal justice. cf. poverty law, constitutional and poverty law, statutory.'},
        {id:20360, name:'indigents: U.S. Supreme Court docketing fee Note: procedural protections for indigents because of their indigency. Typically in matters pertaining to criminal justice. cf. poverty law, constitutional and poverty law, statutory.'},
        {id:20370, name:'indigents: transcript Note: procedural protections for indigents because of their indigency. Typically in matters pertaining to criminal justice. cf. poverty law, constitutional and poverty law, statutory.'},
        {id:20380, name:'indigents: assistance of psychiatrist Note: procedural protections for indigents because of their indigency. Typically in matters pertaining to criminal justice. cf. poverty law, constitutional and poverty law, statutory.'},
        {id:20390, name:'indigents: miscellaneous Note: procedural protections for indigents because of their indigency. Typically in matters pertaining to criminal justice. cf. poverty law, constitutional and poverty law, statutory.'},
        {id:20400, name:'liability, civil rights acts (cf. liability, governmental and liability, nongovernmental; cruel and unusual punishment, non-death penalty) Note: tort actions involving liability that are based on a civil rights act'},
        {id:20410, name:'miscellaneous civil rights (cf. comity: civil rights)'},
        {id:30010, name:'First Amendment, miscellaneous (cf. comity: First Amendment)'},
        {id:30020, name:'commercial speech, excluding attorneys'},
        {id:30030, name:'libel, defamation: defamation of public officials and public and private persons'},
        {id:30040, name:'libel, privacy: true and false light invasions of privacy'},
        {id:30050, name:'legislative investigations: concerning internal security only'},
        {id:30060, name:'federal internal security legislation: Smith, Internal Security, and related federal statutes'},
        {id:30070, name:'loyalty oath or non-Communist affidavit (other than bar applicants, government employees, political party, or teacher)'},
        {id:30080, name:'loyalty oath: bar applicants (cf. admission to bar, state or federal or U.S. Supreme Court)'},
        {id:30090, name:'loyalty oath: government employees'},
        {id:30100, name:'loyalty oath: political party'},
        {id:30110, name:'loyalty oath: teachers'},
        {id:30120, name:'security risks: denial of benefits or dismissal of employees for reasons other than failure to meet loyalty oath requirements'},
        {id:30130, name:'conscientious objectors (cf. military draftee or military active duty) to military service'},
        {id:30140, name:'campaign spending (cf. governmental corruption): Note: financing electoral costs other than as regulated by the Taft-Hartley Act. Typically involves the Federal Election Campaign Act'},
        {id:30150, name:'protest demonstrations (other than as pertains to sit-in demonstrations): demonstrations and other forms of protest based on First Amendment guarantees'},
        {id:30160, name:'free exercise of religion'},
        {id:30170, name:'establishment of religion (other than as pertains to parochiaid:)'},
        {id:30180, name:'parochiaid: government aid to religious schools, or religious requirements in public schools'},
        {id:30190, name:'obscenity, state (cf. comity: privacy): including the regulation of sexually explicit material under the 21st Amendment'},
        {id:30200, name:'obscenity, federal'},
        {id:40010, name:'due process: miscellaneous (cf. loyalty oath), the residual code'},
        {id:40020, name:'due process: hearing or notice (other than as pertains to government employees or prisoners\' rights) Note: hearing may be statutorily based'},
            {id:40030, name:'due process: hearing, government employees'},
            {id:40040, name:'due process: prisoners\' rights and defendants\' rights'},
            {id:40050, name:'due process: impartial decision maker'},
            {id:40060, name:'due process: jurisdiction (jurisdiction over non-resident litigants)'},
            {id:40070, name:'due process: takings clause, or other non-constitutional governmental taking of property'},
            {id:50010, name:'privacy (cf. libel, comity: privacy)'},
            {id:50020, name:'abortion: including contraceptives'},
            {id:50030, name:'right to die'},
            {id:50040, name:'Freedom of Information Act and related federal or state statutes or regulations'},
            {id:60010, name:'attorneys\' and governmental officials\' fees or compensation'},
            {id:60020, name:'commercial speech, attorneys (cf. commercial speech)'},
            {id:60030, name:'admission to a state or federal bar, disbarment, and attorney discipline (cf. loyalty oath: bar applicants)'},
            {id:60040, name:'admission to, or disbarment from, Bar of the U.S. Supreme Court'},
            {id:70010, name:'arbitration (in the context of labor-management or employer-employee relations) (cf. arbitration)'},
            {id:70020, name:'union antitrust: legality of anticompetitive union activity'},
            {id:70030, name:'union or closed shop: includes agency shop litigation'},
            {id:70040, name:'Fair Labor Standards Act'},
            {id:70050, name:'Occupational Safety and Health Act'},
            {id:70060, name:'union-union member dispute (except as pertains to union or closed shop)'},
            {id:70070, name:'labor-management disputes: bargaining'},
            {id:70080, name:'labor-management disputes: employee discharge'},
            {id:70090, name:'labor-management disputes: distribution of union literature'},
            {id:70100, name:'labor-management disputes: representative election'},
            {id:70110, name:'labor-management disputes: antistrike injunction'},
            {id:70120, name:'labor-management disputes: jurisdictional dispute'},
            {id:70130, name:'labor-management disputes: right to organize'},
            {id:70140, name:'labor-management disputes: picketing'},
            {id:70150, name:'labor-management disputes: secondary activity'},
            {id:70160, name:'labor-management disputes: no-strike clause'},
            {id:70170, name:'labor-management disputes: union representatives'},
            {id:70180, name:'labor-management disputes: union trust funds (cf. ERISA)'},
            {id:70190, name:'labor-management disputes: working conditions'},
            {id:70200, name:'labor-management disputes: miscellaneous dispute'},
            {id:70210, name:'miscellaneous union'},
            {id:80010, name:'antitrust (except in the context of mergers and union antitrust)'},
            {id:80020, name:'mergers'},
            {id:80030, name:'bankruptcy (except in the context of priority of federal fiscal claims)'},
            {id:80040, name:'sufficiency of evidence: typically in the context of a jury\'s determination of compensation for injury or death'},
                {id:80050, name:'election of remedies: legal remedies available to injured persons or things'},
                {id:80060, name:'liability, federal governmental: tort or contract actions by or against government or governmental officials other than defense of criminal actions brought under a civil rights action.'},
                {id:80070, name:'liability, other than as in sufficiency of evidence, election of remedies, punitive damages'},
                {id:80080, name:'liability, punitive damages'},
                {id:80090, name:'Employee Retirement Income Security Act (cf. union trust funds)'},
                {id:80100, name:'state or local government tax Note: those challenged on the basis of the supremacy clause and the 21st Amendment may also locate in national supremacy: intergovernmental tax immunity or national supremacy: state tax'},
                {id:80105, name:'state and territorial land claims Note: those challenged on the basis of the supremacy clause and the 21st Amendment may also locate in national supremacy: intergovernmental tax immunity or national supremacy: state tax'},
                {id:80110, name:'state or local government regulation, especially of business (cf. federal pre-emption of state court jurisdiction, federal pre-emption of state legislation or regulation)'},
                {id:80120, name:'federal or state regulation of securities'},
                {id:80130, name:'natural resources - environmental protection (cf. national supremacy: natural resources, national supremacy: pollution)'},
                {id:80140, name:'corruption, governmental or governmental regulation of other than as in campaign spending'},
                {id:80150, name:'zoning: constitutionality of such ordinances, or restrictions on owners\' or lessors\' use of real property'},
                {id:80160, name:'arbitration (other than as pertains to labor-management or employer-employee relations (cf. union arbitration)'},
                {id:80170, name:'federal or state consumer protection: typically under the Truth in Lending; Food, Drug and Cosmetic; and Consumer Protection Credit Acts'},
                {id:80180, name:'patents and copyrights: patent'},
                {id:80190, name:'patents and copyrights: copyright'},
                {id:80200, name:'patents and copyrights: trademark'},
                {id:80210, name:'patents and copyrights: patentability of computer processes'},
                {id:80220, name:'federal or state regulation of transportation regulation: railroad'},
                {id:80230, name:'federal and some few state regulations of transportation regulation: boat'},
                {id:80240, name:'federal and some few state regulation of transportation regulation:truck, or motor carrier'},
                {id:80250, name:'federal and some few state regulation of transportation regulation: pipeline (cf. federal public utilities regulation: gas pipeline)'},
                {id:80260, name:'federal and some few state regulation of transportation regulation: airline'},
                {id:80270, name:'federal and some few state regulation of public utilities regulation: electric power'},
                {id:80280, name:'federal and some few state regulation of public utilities regulation: nuclear power'},
                {id:80290, name:'federal and some few state regulation of public utilities regulation: oil producer'},
                {id:80300, name:'federal and some few state regulation of public utilities regulation: gas producer'},
                {id:80310, name:'federal and some few state regulation of public utilities regulation: gas pipeline (cf. federal transportation regulation: pipeline)'},
                {id:80320, name:'federal and some few state regulation of public utilities regulation: radio and television (cf. cable television)'},
                {id:80330, name:'federal and some few state regulation of public utilities regulation: cable television (cf. radio and television)'},
                {id:80340, name:'federal and some few state regulations of public utilities regulation: telephone or telegraph company'},
                {id:80350, name:'miscellaneous economic regulation'},
                {id:90010, name:'comity, criminal and First Amendment: civil rights Note: propriety of federal court deference to ongoing state judicial or state or federal quasi-judicial proceedings, the abstention doctrine, exhaustion of state provided remedies'},
                {id:90020, name:'comity, criminal and First Amendment: criminal procedure Note: propriety of federal court deference to ongoing state judicial or state or federal quasi-judicial proceedings, the abstention doctrine, exhaustion of state provided remedies'},
                {id:90030, name:'comity, criminal and First Amendment: First Amendment Note: propriety of federal court deference to ongoing state judicial or state or federal quasi-judicial proceedings, the abstention doctrine, exhaustion of state provided remedies'},
                {id:90040, name:'comity, criminal and First Amendment: habeas corpus Note: propriety of federal court deference to ongoing state judicial or state or federal quasi-judicial proceedings, the abstention doctrine, exhaustion of state provided remedies'},
                {id:90050, name:'comity, criminal and First Amendment: military Note: propriety of federal court deference to ongoing state judicial or state or federal quasi-judicial proceedings, the abstention doctrine, exhaustion of state provided remedies'},
                {id:90060, name:'comity, criminal and First Amendment: obscenity Note: propriety of federal court deference to ongoing state judicial or state or federal quasi-judicial proceedings, the abstention doctrine, exhaustion of state provided remedies'},
                {id:90070, name:'comity, criminal and First Amendment: privacy Note: propriety of federal court deference to ongoing state judicial or state or federal quasi-judicial proceedings, the abstention doctrine, exhaustion of state provided remedies'},
                {id:90080, name:'comity, criminal and First Amendment: miscellaneous Note: propriety of federal court deference to ongoing state judicial or state or federal quasi-judicial proceedings, the abstention doctrine, exhaustion of state provided remedies'},
                {id:90090, name:'comity primarily removal cases, civil procedure (cf. comity, criminal and First Amendment); deference to foreign judicial tribunals Note: propriety of federal court deference to ongoing state judicial or state or federal quasi-judicial proceedings, the abstention doctrine, exhaustion of state provided remedies'},
                {id:90100, name:'assessment of costs or damages: as part of a court order'},
                {id:90110, name:'Federal Rules of Civil Procedure including Supreme Court Rules, application of the Federal Rules of Evidence, Federal Rules of Appellate Procedure in civil litigation, Circuit Court Rules, and state rules and admiralty rules'},
                {id:90120, name:'judicial review of administrative agency\'s or administrative official\'s actions and procedures'},
                {id:90130, name:'mootness (cf. standing to sue: live dispute)'},
                {id:90140, name:'venue'},
                {id:90150, name:'no merits: writ improvidently granted Note: use only if the syllabus or the summary holding specifies one of the following bases.'},
                {id:90160, name:'no merits: dismissed or affirmed for want of a substantial or properly presented federal question, or a nonsuit Note: use only if the syllabus or the summary holding specifies one of the following bases.'},
                {id:90170, name:'no merits: dismissed or affirmed for want of jurisdiction (cf. judicial administration: Supreme Court jurisdiction or authority on appeal from federal district courts or courts of appeals) Note: use only if the syllabus or the summary holding specifies one of the following bases.'},
                {id:90180, name:'no merits: adequate non-federal grounds for decision Note: use only if the syllabus or the summary holding specifies one of the following bases.'},
                {id:90190, name:'no merits: remand to determine basis of state or federal court decision (cf. judicial administration: state law) Note: use only if the syllabus or the summary holding specifies one of the following bases.'},
                {id:90200, name:'no merits: miscellaneous Note: use only if the syllabus or the summary holding specifies one of the following bases.'},
                {id:90210, name:'standing to sue: adversary parties'},
                {id:90220, name:'standing to sue: direct injury'},
                {id:90230, name:'standing to sue: legal injury'},
                {id:90240, name:'standing to sue: personal injury'},
                {id:90250, name:'standing to sue: justiciable question'},
                {id:90260, name:'standing to sue: live dispute'},
                {id:90270, name:'standing to sue: parens patriae standing'},
                {id:90280, name:'standing to sue: statutory standing'},
                {id:90290, name:'standing to sue: private or implied cause of action'},
                {id:90300, name:'standing to sue: taxpayer\'s suit'},
                    {id:90310, name:'standing to sue: miscellaneous'},
                    {id:90320, name:'judicial administration: jurisdiction or authority of federal district courts or territorial courts Note: jurisdiction of the federal courts or of the Supreme Court (cf. no merits: dismissed for want of jurisdiction)'},
                    {id:90330, name:'judicial administration: jurisdiction or authority of federal courts of appeals Note: jurisdiction of the federal courts or of the Supreme Court'},
                    {id:90340, name:'judicial administration: Supreme Court jurisdiction or authority on appeal or writ of error, from federal district courts or courts of appeals (cf. 753) Note: jurisdiction of the federal courts or of the Supreme Court'},
                    {id:90350, name:'judicial administration: Supreme Court jurisdiction or authority on appeal or writ of error, from highest state court Note: jurisdiction of the federal courts or of the Supreme Court'},
                    {id:90360, name:'judicial administration: jurisdiction or authority of the Court of Claims Note: jurisdiction of the federal courts or of the Supreme Court'},
                    {id:90370, name:'judicial administration: Supreme Court\'s original jurisdiction Note: jurisdiction of the federal courts or of the Supreme Court'},
                        {id:90380, name:'judicial administration: review of non-final order Note: jurisdiction of the federal courts or of the Supreme Court'},
                        {id:90390, name:'judicial administration: change in state law (cf. no merits: remand to determine basis of state court decision) Note: jurisdiction of the federal courts or of the Supreme Court'},
                        {id:90400, name:'judicial administration: federal question (cf. no merits: dismissed for want of a substantial or properly presented federal question) Note: jurisdiction of the federal courts or of the Supreme Court'},
                        {id:90410, name:'judicial administration: ancillary or pendent jurisdiction Note: jurisdiction of the federal courts or of the Supreme Court'},
                        {id:90420, name:'judicial administration: extraordinary relief (e.g., mandamus, injunction) Note: jurisdiction of the federal courts or of the Supreme Court'},
                        {id:90430, name:'judicial administration: certification (cf. objection to reason for denial of certiorari or appeal) Note: jurisdiction of the federal courts or of the Supreme Court'},
                        {id:90440, name:'judicial administration: resolution of circuit conflict, or conflict between or among other courts Note: jurisdiction of the federal courts or of the Supreme Court'},
                        {id:90450, name:'judicial administration: objection to reason for denial of certiorari or appeal Note: jurisdiction of the federal courts or of the Supreme Court'},
                        {id:90460, name:'judicial administration: collateral estoppel or res judicata Note: jurisdiction of the federal courts or of the Supreme Court'},
                        {id:90470, name:'judicial administration: interpleader Note: jurisdiction of the federal courts or of the Supreme Court'},
                        {id:90480, name:'judicial administration: untimely filing Note: jurisdiction of the federal courts or of the Supreme Court'},
                        {id:90490, name:'judicial administration: Act of State doctrine Note: jurisdiction of the federal courts or of the Supreme Court'},
                        {id:90500, name:'judicial administration: miscellaneous Note: jurisdiction of the federal courts or of the Supreme Court'},
                        {id:90510, name:'Supreme Court\'s certiorari, writ of error, or appeals jurisdiction Note: jurisdiction of the federal courts or of the Supreme Court'},
                            {id:90520, name:'miscellaneous, especially diversity jurisdiction'},
                            {id:100010, name:'federal-state ownership dispute (cf. Submerged Lands Act)'},
                            {id:100020, name:'federal pre-emption of state court jurisdiction Note: almost always found in the context of labor union activity. Does not involve constitutional interpretation. Rests rather on a primary jurisdiction rationale'},
                            {id:100030, name:'federal pre-emption of state legislation or regulation Note: cf. state regulation of business. rarely involves union activity. Does not involve constitutional interpretation unless the Court says it does'},
                            {id:100035, name:'executive authority vis-a-vis congress or the states'},
                            {id:100040, name:'Submerged Lands Act (cf. federal-state ownership dispute)'},
                            {id:100050, name:'national supremacy: commodities Note: in the context of federal-state conflicts involving the general welfare, supremacy, or interstate commerce clauses, the 11th or 21st Amendments, or the enforcement clause of the 14th Amendment. Distinguishable from federal pre-emption because of a constitutional basis for decision.'},
                            {id:100060, name:'national supremacy: intergovernmental tax immunity Note: in the context of federal-state conflicts involving the general welfare, supremacy, or interstate commerce clauses, the 11th or 21st Amendments, or the enforcement clause of the 14th Amendment. Distinguishable from federal pre-emption because of a constitutional basis for decision.'},
                            {id:100070, name:'national supremacy: marital and family relationships and property, including obligation of child support Note: in the context of federal-state conflicts involving the general welfare, supremacy, or interstate commerce clauses, the 11th or 21st Amendments, or the enforcement clause of the 14th Amendment. Distinguishable from federal pre-emption because of a constitutional basis for decision.'},
                            {id:100080, name:'national supremacy: natural resources (cf. natural resources - environmental protection) Note: in the context of federal-state conflicts involving the general welfare, supremacy, or interstate commerce clauses, the 11th or 21st Amendments, or the enforcement clause of the 14th Amendment. Distinguishable from federal pre-emption because of a constitutional basis for decision.'},
                            {id:100090, name:'national supremacy: pollution, air or water (cf. natural resources - environmental protection) Note: in the context of federal-state conflicts involving the general welfare, supremacy, or interstate commerce clauses, the 11th or 21st Amendments, or the enforcement clause of the 14th Amendment. Distinguishable from federal pre-emption because of a constitutional basis for decision.'},
                            {id:100100, name:'national supremacy: public utilities (cf. federal public utilities regulation) Note: in the context of federal-state conflicts involving the general welfare, supremacy, or interstate commerce clauses, the 11th or 21st Amendments, or the enforcement clause of the 14th Amendment. Distinguishable from federal pre-emption because of a constitutional basis for decision.'},
                            {id:100110, name:'national supremacy: state tax (cf. state tax) Note: in the context of federal-state conflicts involving the general welfare, supremacy, or interstate commerce clauses, the 11th or 21st Amendments, or the enforcement clause of the 14th Amendment. Distinguishable from federal pre-emption because of a constitutional basis for decision.'},
                            {id:100120, name:'national supremacy: miscellaneous Note: in the context of federal-state conflicts involving the general welfare, supremacy, or interstate commerce clauses, the 11th or 21st Amendments, or the enforcement clause of the 14th Amendment. Distinguishable from federal pre-emption because of a constitutional basis for decision.'},
                            {id:100130, name:'miscellaneous federalism Note: cf. Indians, state jurisdiction over; comity; adequate non-federal grounds for decision; remand to determine basis of state court decision; judicial administration: Supreme Court jurisdiction or authority on appeal from highest state court, change in state law, or ancillary or pendent jurisdiction'},
                            {id:110010, name:'boundary dispute between states'},
                            {id:110020, name:'non-real property dispute between states'},
                            {id:110030, name:'miscellaneous interstate relations conflict'},
                            {id:120010, name:'federal taxation, typically under provisions of the Internal Revenue Code Note: except as pertains to federal taxation of gifts or priority of federal fiscal claims'},
                            {id:120020, name:'federal taxation of gifts, personal, business, or professional expenses'},
                            {id:120030, name:'priority of federal fiscal claims: over those of the states or private entities'},
                            {id:120040, name:'miscellaneous federal taxation (cf. national supremacy: state tax)'},
                            {id:130010, name:'legislative veto'},
                            {id:130020, name:'miscellaneous'},
                            {id:140010, name:'real property'},
                            {id:140020, name:'personal property'},
                            {id:140030, name:'contracts'},
                            {id:140040, name:'evidence'},
                            {id:140050, name:'civil procedure'},
                            {id:140060, name:'torts'},
                            {id:140070, name:'wills and trusts'},
                            {id:140080, name:'commercial transactions'}
     ];

issue.forEach(function(d) {
    issueById[d.id] = d;
});

var issueArea = [
    {id:1, name:'Criminal Procedure'},
    {id:2, name:'Civil Rights'},
    {id:3, name:'First Amendment'},
    {id:4, name:'Due Process'},
    {id:5, name:'Privacy'},
    {id:6, name:'Attorneys'},
    {id:7, name:'Unions'},
    {id:8, name:'Economic Activity'},
    {id:9, name:'Judicial Power'},
    {id:10, name:'Federalism'},
    {id:11, name:'Interstate Relations'},
    {id:12, name:'Federal Taxation'},
    {id:13, name:'Miscellaneous'},
    {id:14, name:'Private Action'}
];

var issueAreaById = {};
issueArea.forEach(function(d) {
    issueAreaById[d.id] = d;
});

var disposition = [
    {id:1, name:'stay, petition, or motion granted'},
    {id:2, name:'affirmed'},
    {id:3, name:'reversed'},
    {id:4, name:'reversed and remanded'},
    {id:5, name:'vacated and remanded'},
    {id:6, name:'affirmed and reversed (or vacated) in part'},
    {id:7, name:'affirmed and reversed (or vacated) in part and remanded'},
    {id:8, name:'vacated'},
    {id:9, name:'petition denied or appeal dismissed'},
    {id:10, name:'certification to a lower court'},
    {id:11, name:'no disposition'}
    ];

var dispositionById = {};
disposition.forEach(function(d) {
   dispositionById[d.id] = d;
});